# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import fields, is_dataclass
from typing import Any, cast

from .errors import SdkValidationError
from .types import (
    ApiKey,
    AuthApproveRequestBody,
    AuthRegisterOutputBody,
    AuthRegisterRequestBody,
    AuthRejectRequestBody,
    BackfillNodeIPsOutputBody,
    CreateApiKeyOutputBody,
    CreateApiKeyRequestBody,
    CreatePreAuthKeyRequestBody,
    CreateUserRequestBody,
    DebugCreateNodeRequestBody,
    ErrorDetail,
    ErrorModel,
    ExpireApiKeyRequestBody,
    ExpireNodeRequestBody,
    ExpirePreAuthKeyRequestBody,
    HealthResponseBody,
    ListApiKeysOutputBody,
    ListNodesOutputBody,
    ListPreAuthKeysOutputBody,
    ListUsersOutputBody,
    Node,
    NodeOutputBody,
    NodePreAuthKey,
    PolicyRequestBody,
    PolicyResponseBody,
    PreAuthKey,
    PreAuthKeyOutputBody,
    SetApprovedRoutesRequestBody,
    SetTagsRequestBody,
    User,
    UserOutputBody,
)
from .validation import validate_date_time, validate_uri
from .wire import to_wire

MODEL_CONSTRUCTION_STYLE = "pydantic"

_SCHEMAS: dict[str, Any] = {
    "ApiKey": {
        "type": "object",
        "required": ["id", "prefix", "expiration", "createdAt", "lastSeen"],
        "properties": {
            "createdAt": {
                "python": "created_at",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "expiration": {
                "python": "expiration",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "id": {"python": "id", "type": "string"},
            "lastSeen": {
                "python": "last_seen",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "prefix": {"python": "prefix", "type": "string"},
        },
    },
    "AuthApproveOutputBody": {"type": "object"},
    "AuthApproveRequestBody": {
        "type": "object",
        "properties": {"authId": {"python": "auth_id", "type": "string"}},
    },
    "AuthRegisterOutputBody": {
        "type": "object",
        "required": ["node"],
        "properties": {"node": {"python": "node", "ref": "Node"}},
    },
    "AuthRegisterRequestBody": {
        "type": "object",
        "properties": {
            "authId": {"python": "auth_id", "type": "string"},
            "user": {"python": "user", "type": "string"},
        },
    },
    "AuthRejectOutputBody": {"type": "object"},
    "AuthRejectRequestBody": {
        "type": "object",
        "properties": {"authId": {"python": "auth_id", "type": "string"}},
    },
    "BackfillNodeIPsOutputBody": {
        "type": "object",
        "required": ["changes"],
        "properties": {
            "changes": {"python": "changes", "type": "array", "items": {"type": "string"}}
        },
    },
    "CheckPolicyOutputBody": {"type": "object"},
    "CreateApiKeyOutputBody": {
        "type": "object",
        "required": ["apiKey"],
        "properties": {"apiKey": {"python": "api_key", "type": "string"}},
    },
    "CreateApiKeyRequestBody": {
        "type": "object",
        "properties": {
            "expiration": {"python": "expiration", "type": "string", "format": "date-time"}
        },
    },
    "CreatePreAuthKeyRequestBody": {
        "type": "object",
        "properties": {
            "aclTags": {
                "python": "acl_tags",
                "type": "array",
                "nullable": True,
                "items": {"type": "string"},
            },
            "ephemeral": {"python": "ephemeral", "type": "boolean"},
            "expiration": {"python": "expiration", "type": "string", "format": "date-time"},
            "reusable": {"python": "reusable", "type": "boolean"},
            "user": {"python": "user", "type": "string"},
        },
    },
    "CreateUserRequestBody": {
        "type": "object",
        "properties": {
            "displayName": {"python": "display_name", "type": "string"},
            "email": {"python": "email", "type": "string"},
            "name": {"python": "name", "type": "string"},
            "pictureUrl": {"python": "picture_url", "type": "string"},
        },
    },
    "DebugCreateNodeRequestBody": {
        "type": "object",
        "properties": {
            "key": {"python": "key", "type": "string"},
            "name": {"python": "name", "type": "string"},
            "routes": {
                "python": "routes",
                "type": "array",
                "nullable": True,
                "items": {"type": "string"},
            },
            "user": {"python": "user", "type": "string"},
        },
    },
    "DeleteApiKeyOutputBody": {"type": "object"},
    "DeleteNodeOutputBody": {"type": "object"},
    "DeletePreAuthKeyOutputBody": {"type": "object"},
    "DeleteUserOutputBody": {"type": "object"},
    "ErrorDetail": {
        "type": "object",
        "properties": {
            "location": {"python": "location", "type": "string"},
            "message": {"python": "message", "type": "string"},
            "value": {"python": "value"},
        },
    },
    "ErrorModel": {
        "type": "object",
        "properties": {
            "detail": {"python": "detail", "type": "string"},
            "errors": {
                "python": "errors",
                "type": "array",
                "nullable": True,
                "items": {"ref": "ErrorDetail"},
            },
            "instance": {"python": "instance", "type": "string", "format": "uri"},
            "status": {"python": "status", "type": "integer"},
            "title": {"python": "title", "type": "string"},
            "type": {"python": "type", "type": "string", "format": "uri"},
        },
    },
    "ExpireApiKeyOutputBody": {"type": "object"},
    "ExpireApiKeyRequestBody": {
        "type": "object",
        "properties": {
            "id": {"python": "id", "type": "string"},
            "prefix": {"python": "prefix", "type": "string"},
        },
    },
    "ExpireNodeRequestBody": {
        "type": "object",
        "properties": {
            "disableExpiry": {"python": "disable_expiry", "type": "boolean"},
            "expiry": {"python": "expiry", "type": "string", "format": "date-time"},
        },
    },
    "ExpirePreAuthKeyOutputBody": {"type": "object"},
    "ExpirePreAuthKeyRequestBody": {
        "type": "object",
        "properties": {"id": {"python": "id", "type": "string"}},
    },
    "HealthResponseBody": {
        "type": "object",
        "required": ["databaseConnectivity"],
        "properties": {
            "databaseConnectivity": {"python": "database_connectivity", "type": "boolean"}
        },
    },
    "ListApiKeysOutputBody": {
        "type": "object",
        "required": ["apiKeys"],
        "properties": {
            "apiKeys": {"python": "api_keys", "type": "array", "items": {"ref": "ApiKey"}}
        },
    },
    "ListNodesOutputBody": {
        "type": "object",
        "required": ["nodes"],
        "properties": {"nodes": {"python": "nodes", "type": "array", "items": {"ref": "Node"}}},
    },
    "ListPreAuthKeysOutputBody": {
        "type": "object",
        "required": ["preAuthKeys"],
        "properties": {
            "preAuthKeys": {
                "python": "pre_auth_keys",
                "type": "array",
                "items": {"ref": "PreAuthKey"},
            }
        },
    },
    "ListUsersOutputBody": {
        "type": "object",
        "required": ["users"],
        "properties": {"users": {"python": "users", "type": "array", "items": {"ref": "User"}}},
    },
    "Node": {
        "type": "object",
        "required": [
            "id",
            "machineKey",
            "nodeKey",
            "discoKey",
            "ipAddresses",
            "name",
            "user",
            "lastSeen",
            "expiry",
            "preAuthKey",
            "createdAt",
            "registerMethod",
            "givenName",
            "online",
            "approvedRoutes",
            "availableRoutes",
            "subnetRoutes",
            "tags",
        ],
        "properties": {
            "approvedRoutes": {
                "python": "approved_routes",
                "type": "array",
                "items": {"type": "string"},
            },
            "availableRoutes": {
                "python": "available_routes",
                "type": "array",
                "items": {"type": "string"},
            },
            "createdAt": {"python": "created_at", "type": "string", "format": "date-time"},
            "discoKey": {"python": "disco_key", "type": "string"},
            "expiry": {
                "python": "expiry",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "givenName": {"python": "given_name", "type": "string"},
            "id": {"python": "id", "type": "string"},
            "ipAddresses": {"python": "ip_addresses", "type": "array", "items": {"type": "string"}},
            "lastSeen": {
                "python": "last_seen",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "machineKey": {"python": "machine_key", "type": "string"},
            "name": {"python": "name", "type": "string"},
            "nodeKey": {"python": "node_key", "type": "string"},
            "online": {"python": "online", "type": "boolean"},
            "preAuthKey": {"python": "pre_auth_key", "ref": "NodePreAuthKey"},
            "registerMethod": {"python": "register_method", "type": "string"},
            "subnetRoutes": {
                "python": "subnet_routes",
                "type": "array",
                "items": {"type": "string"},
            },
            "tags": {"python": "tags", "type": "array", "items": {"type": "string"}},
            "user": {"python": "user", "ref": "User"},
        },
    },
    "NodeOutputBody": {
        "type": "object",
        "required": ["node"],
        "properties": {"node": {"python": "node", "ref": "Node"}},
    },
    "NodePreAuthKey": {
        "type": "object",
        "required": [
            "user",
            "id",
            "key",
            "reusable",
            "ephemeral",
            "used",
            "expiration",
            "createdAt",
            "aclTags",
        ],
        "properties": {
            "aclTags": {"python": "acl_tags", "type": "array", "items": {"type": "string"}},
            "createdAt": {
                "python": "created_at",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "ephemeral": {"python": "ephemeral", "type": "boolean"},
            "expiration": {
                "python": "expiration",
                "type": "string",
                "nullable": True,
                "format": "date-time",
            },
            "id": {"python": "id", "type": "string"},
            "key": {"python": "key", "type": "string"},
            "reusable": {"python": "reusable", "type": "boolean"},
            "used": {"python": "used", "type": "boolean"},
            "user": {"python": "user", "ref": "User"},
        },
    },
    "PolicyRequestBody": {
        "type": "object",
        "properties": {"policy": {"python": "policy", "type": "string"}},
    },
    "PolicyResponseBody": {
        "type": "object",
        "required": ["policy", "updatedAt"],
        "properties": {
            "policy": {"python": "policy", "type": "string"},
            "updatedAt": {"python": "updated_at", "type": "string", "format": "date-time"},
        },
    },
    "PreAuthKey": {
        "type": "object",
        "required": [
            "user",
            "id",
            "key",
            "reusable",
            "ephemeral",
            "used",
            "expiration",
            "createdAt",
            "aclTags",
        ],
        "properties": {
            "aclTags": {"python": "acl_tags", "type": "array", "items": {"type": "string"}},
            "createdAt": {"python": "created_at", "type": "string", "format": "date-time"},
            "ephemeral": {"python": "ephemeral", "type": "boolean"},
            "expiration": {"python": "expiration", "type": "string", "format": "date-time"},
            "id": {"python": "id", "type": "string"},
            "key": {"python": "key", "type": "string"},
            "reusable": {"python": "reusable", "type": "boolean"},
            "used": {"python": "used", "type": "boolean"},
            "user": {"python": "user", "ref": "User"},
        },
    },
    "PreAuthKeyOutputBody": {
        "type": "object",
        "required": ["preAuthKey"],
        "properties": {"preAuthKey": {"python": "pre_auth_key", "ref": "PreAuthKey"}},
    },
    "SetApprovedRoutesRequestBody": {
        "type": "object",
        "properties": {
            "routes": {
                "python": "routes",
                "type": "array",
                "nullable": True,
                "items": {"type": "string"},
            }
        },
    },
    "SetTagsRequestBody": {
        "type": "object",
        "properties": {
            "tags": {
                "python": "tags",
                "type": "array",
                "nullable": True,
                "items": {"type": "string"},
            }
        },
    },
    "User": {
        "type": "object",
        "required": [
            "id",
            "name",
            "createdAt",
            "displayName",
            "email",
            "providerId",
            "provider",
            "profilePicUrl",
        ],
        "properties": {
            "createdAt": {"python": "created_at", "type": "string", "format": "date-time"},
            "displayName": {"python": "display_name", "type": "string"},
            "email": {"python": "email", "type": "string"},
            "id": {"python": "id", "type": "string"},
            "name": {"python": "name", "type": "string"},
            "profilePicUrl": {"python": "profile_pic_url", "type": "string"},
            "provider": {"python": "provider", "type": "string"},
            "providerId": {"python": "provider_id", "type": "string"},
        },
    },
    "UserOutputBody": {
        "type": "object",
        "required": ["user"],
        "properties": {"user": {"python": "user", "ref": "User"}},
    },
}
_MODEL_TYPES: dict[str, type[Any]] = {
    "ApiKey": ApiKey,
    "AuthApproveRequestBody": AuthApproveRequestBody,
    "AuthRegisterOutputBody": AuthRegisterOutputBody,
    "AuthRegisterRequestBody": AuthRegisterRequestBody,
    "AuthRejectRequestBody": AuthRejectRequestBody,
    "BackfillNodeIPsOutputBody": BackfillNodeIPsOutputBody,
    "CreateApiKeyOutputBody": CreateApiKeyOutputBody,
    "CreateApiKeyRequestBody": CreateApiKeyRequestBody,
    "CreatePreAuthKeyRequestBody": CreatePreAuthKeyRequestBody,
    "CreateUserRequestBody": CreateUserRequestBody,
    "DebugCreateNodeRequestBody": DebugCreateNodeRequestBody,
    "ErrorDetail": ErrorDetail,
    "ErrorModel": ErrorModel,
    "ExpireApiKeyRequestBody": ExpireApiKeyRequestBody,
    "ExpireNodeRequestBody": ExpireNodeRequestBody,
    "ExpirePreAuthKeyRequestBody": ExpirePreAuthKeyRequestBody,
    "HealthResponseBody": HealthResponseBody,
    "ListApiKeysOutputBody": ListApiKeysOutputBody,
    "ListNodesOutputBody": ListNodesOutputBody,
    "ListPreAuthKeysOutputBody": ListPreAuthKeysOutputBody,
    "ListUsersOutputBody": ListUsersOutputBody,
    "Node": Node,
    "NodeOutputBody": NodeOutputBody,
    "NodePreAuthKey": NodePreAuthKey,
    "PolicyRequestBody": PolicyRequestBody,
    "PolicyResponseBody": PolicyResponseBody,
    "PreAuthKey": PreAuthKey,
    "PreAuthKeyOutputBody": PreAuthKeyOutputBody,
    "SetApprovedRoutesRequestBody": SetApprovedRoutesRequestBody,
    "SetTagsRequestBody": SetTagsRequestBody,
    "User": User,
    "UserOutputBody": UserOutputBody,
}
# Values that can never hold a nested model, so they need no cycle bookkeeping.
_SCALARS = (str, bytes, bool, int, float)


def _as_mapping(value: object) -> Mapping[str, object]:
    if isinstance(value, Mapping):
        return value
    if is_dataclass(value) and not isinstance(value, type):
        return {field.name: getattr(value, field.name) for field in fields(value)}
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return model_dump(by_alias=True, exclude_unset=True)
    raise TypeError("model construction values must be mappings or model instances")


def _field_value(value: object, wire_name: str, python_name: str) -> tuple[bool, object]:
    mapping = _as_mapping(value)
    if python_name in mapping:
        return True, mapping[python_name]
    if wire_name in mapping:
        return True, mapping[wire_name]
    return False, None


def _property_name(wire_name: str, schema: Mapping[str, Any]) -> str:
    return str(schema.get("python", wire_name))


def _child_field(field: str, child: str) -> str:
    return f"{field}.{child}" if field else child


def _resolve(schema: Mapping[str, Any]) -> tuple[str | None, Mapping[str, Any]]:
    """Follows a reference chain to the named schema it points at."""
    name: str | None = None
    visited: set[str] = set()
    reference = schema.get("ref")
    while isinstance(reference, str) and reference not in visited:
        visited.add(reference)
        name = reference
        target = _SCHEMAS.get(reference)
        schema = target if isinstance(target, Mapping) else {}
        reference = schema.get("ref")
    return name, schema


def _select_member(
    value: object,
    members: list[Any],
    field: str,
    active: set[tuple[int, int]],
) -> Mapping[str, Any] | None:
    """Returns the first union member the value satisfies, or raises its error."""
    rejection: SdkValidationError | None = None
    for member in members:
        if not isinstance(member, Mapping):
            continue
        try:
            _validate_node(value, member, field, active)
        except SdkValidationError as error:
            rejection = rejection or error
            continue
        return member
    if rejection is not None:
        raise rejection
    return None


def _validate_node(
    value: object,
    schema: Mapping[str, Any],
    field: str,
    active: set[tuple[int, int]],
) -> None:
    _name, resolved = _resolve(schema)
    if value is None:
        return

    # Recursive schemas describe finite values, so every node is validated. Only
    # a value that contains itself repeats a (value, schema) pair, and that can
    # never be constructed into a model.
    if not isinstance(value, _SCALARS):
        visit = (id(value), id(resolved))
        if visit in active:
            raise SdkValidationError(
                field,
                "recursion",
                f"Validation failed for '{field}': model value contains itself",
            )
        active = {*active, visit}

    for member in resolved.get("allOf", ()):
        if isinstance(member, Mapping):
            _validate_node(value, member, field, active)

    members = resolved.get("oneOf") or resolved.get("anyOf")
    if isinstance(members, list) and members:
        _select_member(value, members, field, active)
        return

    properties = resolved.get("properties")
    if isinstance(properties, Mapping):
        required = resolved.get("required", ())
        for wire_name in required if isinstance(required, list) else ():
            property_schema = properties.get(wire_name)
            python_name = (
                _property_name(wire_name, property_schema)
                if isinstance(property_schema, Mapping)
                else wire_name
            )
            present, property_value = _field_value(value, wire_name, python_name)
            if (
                not present
                or property_value is None
                and not (
                    isinstance(property_schema, Mapping) and property_schema.get("nullable") is True
                )
            ):
                raise SdkValidationError(
                    _child_field(field, wire_name),
                    "required",
                    f"Missing required property '{wire_name}'",
                )

        for wire_name, property_schema in properties.items():
            if not isinstance(property_schema, Mapping):
                continue
            present, property_value = _field_value(
                value, wire_name, _property_name(wire_name, property_schema)
            )
            if present:
                _validate_node(
                    property_value,
                    property_schema,
                    _child_field(field, wire_name),
                    active,
                )

    additional = resolved.get("additionalProperties")
    if isinstance(additional, Mapping) and isinstance(value, Mapping):
        known = {
            name
            for wire_name, property_schema in (properties or {}).items()
            if isinstance(property_schema, Mapping)
            for name in (wire_name, _property_name(wire_name, property_schema))
        }
        for key, property_value in value.items():
            if key not in known:
                _validate_node(property_value, additional, _child_field(field, key), active)

    items = resolved.get("items")
    if isinstance(value, (list, tuple)) and isinstance(items, Mapping):
        for index, item in enumerate(value):
            _validate_node(item, items, _child_field(field, str(index)), active)

    if resolved.get("format") == "uri":
        validate_uri(field, cast(str, value))

    if resolved.get("format") == "date-time":
        validate_date_time(field, cast(str, value))


def _build(type_name: str | None, values: dict[str, object]) -> object:
    model_type = _MODEL_TYPES.get(type_name) if type_name is not None else None
    if model_type is None or MODEL_CONSTRUCTION_STYLE == "typeddict":
        return values
    return model_type(**values)


def _hydrate(value: object, schema: Mapping[str, Any], field: str) -> object:
    """Builds the public value for one schema node, constructing nested models."""
    name, resolved = _resolve(schema)
    if value is None:
        return None

    members = resolved.get("oneOf") or resolved.get("anyOf")
    if isinstance(members, list) and members:
        member = _select_member(value, members, field, set())
        return value if member is None else _hydrate(value, member, field)

    properties = resolved.get("properties")
    if isinstance(properties, Mapping):
        values: dict[str, object] = {}
        for wire_name, property_schema in properties.items():
            if not isinstance(property_schema, Mapping):
                continue
            python_name = _property_name(wire_name, property_schema)
            present, property_value = _field_value(value, wire_name, python_name)
            if present:
                values[python_name] = _hydrate(
                    property_value, property_schema, _child_field(field, wire_name)
                )
        return _build(name, values)

    additional = resolved.get("additionalProperties")
    if isinstance(additional, Mapping) and isinstance(value, Mapping):
        return {
            key: _hydrate(item, additional, _child_field(field, key)) for key, item in value.items()
        }

    items = resolved.get("items")
    if isinstance(items, Mapping) and isinstance(value, (list, tuple)):
        return [
            _hydrate(item, items, _child_field(field, str(index)))
            for index, item in enumerate(value)
        ]

    return value


def _construct_model(value: object, type_name: str) -> object:
    if type_name not in _MODEL_TYPES:
        raise ValueError(f"unknown model type: {type_name}")
    _validate_node(value, {"ref": type_name}, "", set())
    if MODEL_CONSTRUCTION_STYLE == "pydantic":
        # Pydantic owns nested construction: its declared field types already
        # describe every referenced model. The wire remapper first restores the
        # spec spelling that the generated aliases and validators expect.
        return _MODEL_TYPES[type_name].model_validate(to_wire(value, type_name))
    return _hydrate(value, {"ref": type_name}, "")


def create_api_key(value: Mapping[str, object]) -> ApiKey:
    """Construct one ApiKey after applying its schema constraints."""
    return cast(ApiKey, _construct_model(value, "ApiKey"))


def create_auth_approve_request_body(value: Mapping[str, object]) -> AuthApproveRequestBody:
    """Construct one AuthApproveRequestBody after applying its schema constraints."""
    return cast(AuthApproveRequestBody, _construct_model(value, "AuthApproveRequestBody"))


def create_auth_register_output_body(value: Mapping[str, object]) -> AuthRegisterOutputBody:
    """Construct one AuthRegisterOutputBody after applying its schema constraints."""
    return cast(AuthRegisterOutputBody, _construct_model(value, "AuthRegisterOutputBody"))


def create_auth_register_request_body(value: Mapping[str, object]) -> AuthRegisterRequestBody:
    """Construct one AuthRegisterRequestBody after applying its schema constraints."""
    return cast(AuthRegisterRequestBody, _construct_model(value, "AuthRegisterRequestBody"))


def create_auth_reject_request_body(value: Mapping[str, object]) -> AuthRejectRequestBody:
    """Construct one AuthRejectRequestBody after applying its schema constraints."""
    return cast(AuthRejectRequestBody, _construct_model(value, "AuthRejectRequestBody"))


def create_backfill_node_ips_output_body(value: Mapping[str, object]) -> BackfillNodeIPsOutputBody:
    """Construct one BackfillNodeIPsOutputBody after applying its schema constraints."""
    return cast(BackfillNodeIPsOutputBody, _construct_model(value, "BackfillNodeIPsOutputBody"))


def create_create_api_key_output_body(value: Mapping[str, object]) -> CreateApiKeyOutputBody:
    """Construct one CreateApiKeyOutputBody after applying its schema constraints."""
    return cast(CreateApiKeyOutputBody, _construct_model(value, "CreateApiKeyOutputBody"))


def create_create_api_key_request_body(value: Mapping[str, object]) -> CreateApiKeyRequestBody:
    """Construct one CreateApiKeyRequestBody after applying its schema constraints."""
    return cast(CreateApiKeyRequestBody, _construct_model(value, "CreateApiKeyRequestBody"))


def create_create_pre_auth_key_request_body(
    value: Mapping[str, object],
) -> CreatePreAuthKeyRequestBody:
    """Construct one CreatePreAuthKeyRequestBody after applying its schema constraints."""
    return cast(CreatePreAuthKeyRequestBody, _construct_model(value, "CreatePreAuthKeyRequestBody"))


def create_create_user_request_body(value: Mapping[str, object]) -> CreateUserRequestBody:
    """Construct one CreateUserRequestBody after applying its schema constraints."""
    return cast(CreateUserRequestBody, _construct_model(value, "CreateUserRequestBody"))


def create_debug_create_node_request_body(
    value: Mapping[str, object],
) -> DebugCreateNodeRequestBody:
    """Construct one DebugCreateNodeRequestBody after applying its schema constraints."""
    return cast(DebugCreateNodeRequestBody, _construct_model(value, "DebugCreateNodeRequestBody"))


def create_error_detail(value: Mapping[str, object]) -> ErrorDetail:
    """Construct one ErrorDetail after applying its schema constraints."""
    return cast(ErrorDetail, _construct_model(value, "ErrorDetail"))


def create_error_model(value: Mapping[str, object]) -> ErrorModel:
    """Construct one ErrorModel after applying its schema constraints."""
    return cast(ErrorModel, _construct_model(value, "ErrorModel"))


def create_expire_api_key_request_body(value: Mapping[str, object]) -> ExpireApiKeyRequestBody:
    """Construct one ExpireApiKeyRequestBody after applying its schema constraints."""
    return cast(ExpireApiKeyRequestBody, _construct_model(value, "ExpireApiKeyRequestBody"))


def create_expire_node_request_body(value: Mapping[str, object]) -> ExpireNodeRequestBody:
    """Construct one ExpireNodeRequestBody after applying its schema constraints."""
    return cast(ExpireNodeRequestBody, _construct_model(value, "ExpireNodeRequestBody"))


def create_expire_pre_auth_key_request_body(
    value: Mapping[str, object],
) -> ExpirePreAuthKeyRequestBody:
    """Construct one ExpirePreAuthKeyRequestBody after applying its schema constraints."""
    return cast(ExpirePreAuthKeyRequestBody, _construct_model(value, "ExpirePreAuthKeyRequestBody"))


def create_health_response_body(value: Mapping[str, object]) -> HealthResponseBody:
    """Construct one HealthResponseBody after applying its schema constraints."""
    return cast(HealthResponseBody, _construct_model(value, "HealthResponseBody"))


def create_list_api_keys_output_body(value: Mapping[str, object]) -> ListApiKeysOutputBody:
    """Construct one ListApiKeysOutputBody after applying its schema constraints."""
    return cast(ListApiKeysOutputBody, _construct_model(value, "ListApiKeysOutputBody"))


def create_list_nodes_output_body(value: Mapping[str, object]) -> ListNodesOutputBody:
    """Construct one ListNodesOutputBody after applying its schema constraints."""
    return cast(ListNodesOutputBody, _construct_model(value, "ListNodesOutputBody"))


def create_list_pre_auth_keys_output_body(value: Mapping[str, object]) -> ListPreAuthKeysOutputBody:
    """Construct one ListPreAuthKeysOutputBody after applying its schema constraints."""
    return cast(ListPreAuthKeysOutputBody, _construct_model(value, "ListPreAuthKeysOutputBody"))


def create_list_users_output_body(value: Mapping[str, object]) -> ListUsersOutputBody:
    """Construct one ListUsersOutputBody after applying its schema constraints."""
    return cast(ListUsersOutputBody, _construct_model(value, "ListUsersOutputBody"))


def create_node(value: Mapping[str, object]) -> Node:
    """Construct one Node after applying its schema constraints."""
    return cast(Node, _construct_model(value, "Node"))


def create_node_output_body(value: Mapping[str, object]) -> NodeOutputBody:
    """Construct one NodeOutputBody after applying its schema constraints."""
    return cast(NodeOutputBody, _construct_model(value, "NodeOutputBody"))


def create_node_pre_auth_key(value: Mapping[str, object]) -> NodePreAuthKey:
    """Construct one NodePreAuthKey after applying its schema constraints."""
    return cast(NodePreAuthKey, _construct_model(value, "NodePreAuthKey"))


def create_policy_request_body(value: Mapping[str, object]) -> PolicyRequestBody:
    """Construct one PolicyRequestBody after applying its schema constraints."""
    return cast(PolicyRequestBody, _construct_model(value, "PolicyRequestBody"))


def create_policy_response_body(value: Mapping[str, object]) -> PolicyResponseBody:
    """Construct one PolicyResponseBody after applying its schema constraints."""
    return cast(PolicyResponseBody, _construct_model(value, "PolicyResponseBody"))


def create_pre_auth_key(value: Mapping[str, object]) -> PreAuthKey:
    """Construct one PreAuthKey after applying its schema constraints."""
    return cast(PreAuthKey, _construct_model(value, "PreAuthKey"))


def create_pre_auth_key_output_body(value: Mapping[str, object]) -> PreAuthKeyOutputBody:
    """Construct one PreAuthKeyOutputBody after applying its schema constraints."""
    return cast(PreAuthKeyOutputBody, _construct_model(value, "PreAuthKeyOutputBody"))


def create_set_approved_routes_request_body(
    value: Mapping[str, object],
) -> SetApprovedRoutesRequestBody:
    """Construct one SetApprovedRoutesRequestBody after applying its schema constraints."""
    return cast(
        SetApprovedRoutesRequestBody, _construct_model(value, "SetApprovedRoutesRequestBody")
    )


def create_set_tags_request_body(value: Mapping[str, object]) -> SetTagsRequestBody:
    """Construct one SetTagsRequestBody after applying its schema constraints."""
    return cast(SetTagsRequestBody, _construct_model(value, "SetTagsRequestBody"))


def create_user(value: Mapping[str, object]) -> User:
    """Construct one User after applying its schema constraints."""
    return cast(User, _construct_model(value, "User"))


def create_user_output_body(value: Mapping[str, object]) -> UserOutputBody:
    """Construct one UserOutputBody after applying its schema constraints."""
    return cast(UserOutputBody, _construct_model(value, "UserOutputBody"))


def serialize_model(value: object, type_name: str) -> object:
    """Serialize a constructed model using the generated wire-name registry."""
    if type_name not in _MODEL_TYPES:
        raise ValueError(f"unknown model type: {type_name}")
    return to_wire(value, type_name)


def deserialize_model(value: object, type_name: str) -> object:
    """Validate and construct a model from its JSON-shaped representation."""
    return _construct_model(value, type_name)


__all__ = [
    "MODEL_CONSTRUCTION_STYLE",
    "create_api_key",
    "create_auth_approve_request_body",
    "create_auth_register_output_body",
    "create_auth_register_request_body",
    "create_auth_reject_request_body",
    "create_backfill_node_ips_output_body",
    "create_create_api_key_output_body",
    "create_create_api_key_request_body",
    "create_create_pre_auth_key_request_body",
    "create_create_user_request_body",
    "create_debug_create_node_request_body",
    "create_error_detail",
    "create_error_model",
    "create_expire_api_key_request_body",
    "create_expire_node_request_body",
    "create_expire_pre_auth_key_request_body",
    "create_health_response_body",
    "create_list_api_keys_output_body",
    "create_list_nodes_output_body",
    "create_list_pre_auth_keys_output_body",
    "create_list_users_output_body",
    "create_node",
    "create_node_output_body",
    "create_node_pre_auth_key",
    "create_policy_request_body",
    "create_policy_response_body",
    "create_pre_auth_key",
    "create_pre_auth_key_output_body",
    "create_set_approved_routes_request_body",
    "create_set_tags_request_body",
    "create_user",
    "create_user_output_body",
    "deserialize_model",
    "serialize_model",
]
