# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from dataclasses import fields, is_dataclass
from enum import Enum
from typing import Any

from ._client_config import NOT_GIVEN, _wire_scalar
from .errors import SdkValidationError

_MISSING = object()


_WIRE_SCHEMAS: dict[str, tuple[Any, dict[str, tuple[str, str | None]]]] = {
    "ApiKey": (
        None,
        {
            "created_at": ("createdAt", None),
            "expiration": ("expiration", None),
            "id": ("id", None),
            "last_seen": ("lastSeen", None),
            "prefix": ("prefix", None),
        },
    ),
    "AuthApproveRequestBody": (
        None,
        {
            "auth_id": ("authId", None),
        },
    ),
    "AuthRegisterOutputBody": (
        None,
        {
            "node": ("node", "Node"),
        },
    ),
    "AuthRegisterRequestBody": (
        None,
        {
            "auth_id": ("authId", None),
            "user": ("user", None),
        },
    ),
    "AuthRejectRequestBody": (
        None,
        {
            "auth_id": ("authId", None),
        },
    ),
    "BackfillNodeIPsOutputBody": (
        None,
        {
            "changes": ("changes", None),
        },
    ),
    "CreateApiKeyOutputBody": (
        None,
        {
            "api_key": ("apiKey", None),
        },
    ),
    "CreateApiKeyRequestBody": (
        None,
        {
            "expiration": ("expiration", None),
        },
    ),
    "CreatePreAuthKeyRequestBody": (
        None,
        {
            "acl_tags": ("aclTags", None),
            "ephemeral": ("ephemeral", None),
            "expiration": ("expiration", None),
            "reusable": ("reusable", None),
            "user": ("user", None),
        },
    ),
    "CreateUserRequestBody": (
        None,
        {
            "display_name": ("displayName", None),
            "email": ("email", None),
            "name": ("name", None),
            "picture_url": ("pictureUrl", None),
        },
    ),
    "DebugCreateNodeRequestBody": (
        None,
        {
            "key": ("key", None),
            "name": ("name", None),
            "routes": ("routes", None),
            "user": ("user", None),
        },
    ),
    "ErrorDetail": (
        None,
        {
            "location": ("location", None),
            "message": ("message", None),
            "value": ("value", None),
        },
    ),
    "ErrorModel": (
        None,
        {
            "detail": ("detail", None),
            "errors": ("errors", "ErrorDetail"),
            "instance": ("instance", None),
            "status": ("status", None),
            "title": ("title", None),
            "type": ("type", None),
        },
    ),
    "ExpireApiKeyRequestBody": (
        None,
        {
            "id": ("id", None),
            "prefix": ("prefix", None),
        },
    ),
    "ExpireNodeRequestBody": (
        None,
        {
            "disable_expiry": ("disableExpiry", None),
            "expiry": ("expiry", None),
        },
    ),
    "ExpirePreAuthKeyRequestBody": (
        None,
        {
            "id": ("id", None),
        },
    ),
    "HealthResponseBody": (
        None,
        {
            "database_connectivity": ("databaseConnectivity", None),
        },
    ),
    "ListApiKeysOutputBody": (
        None,
        {
            "api_keys": ("apiKeys", "ApiKey"),
        },
    ),
    "ListNodesOutputBody": (
        None,
        {
            "nodes": ("nodes", "Node"),
        },
    ),
    "ListPreAuthKeysOutputBody": (
        None,
        {
            "pre_auth_keys": ("preAuthKeys", "PreAuthKey"),
        },
    ),
    "ListUsersOutputBody": (
        None,
        {
            "users": ("users", "User"),
        },
    ),
    "Node": (
        None,
        {
            "approved_routes": ("approvedRoutes", None),
            "available_routes": ("availableRoutes", None),
            "created_at": ("createdAt", None),
            "disco_key": ("discoKey", None),
            "expiry": ("expiry", None),
            "given_name": ("givenName", None),
            "id": ("id", None),
            "ip_addresses": ("ipAddresses", None),
            "last_seen": ("lastSeen", None),
            "machine_key": ("machineKey", None),
            "name": ("name", None),
            "node_key": ("nodeKey", None),
            "online": ("online", None),
            "pre_auth_key": ("preAuthKey", "NodePreAuthKey"),
            "register_method": ("registerMethod", None),
            "subnet_routes": ("subnetRoutes", None),
            "tags": ("tags", None),
            "user": ("user", "User"),
        },
    ),
    "NodeOutputBody": (
        None,
        {
            "node": ("node", "Node"),
        },
    ),
    "NodePreAuthKey": (
        None,
        {
            "acl_tags": ("aclTags", None),
            "created_at": ("createdAt", None),
            "ephemeral": ("ephemeral", None),
            "expiration": ("expiration", None),
            "id": ("id", None),
            "key": ("key", None),
            "reusable": ("reusable", None),
            "used": ("used", None),
            "user": ("user", "User"),
        },
    ),
    "PolicyRequestBody": (
        None,
        {
            "policy": ("policy", None),
        },
    ),
    "PolicyResponseBody": (
        None,
        {
            "policy": ("policy", None),
            "updated_at": ("updatedAt", None),
        },
    ),
    "PreAuthKey": (
        None,
        {
            "acl_tags": ("aclTags", None),
            "created_at": ("createdAt", None),
            "ephemeral": ("ephemeral", None),
            "expiration": ("expiration", None),
            "id": ("id", None),
            "key": ("key", None),
            "reusable": ("reusable", None),
            "used": ("used", None),
            "user": ("user", "User"),
        },
    ),
    "PreAuthKeyOutputBody": (
        None,
        {
            "pre_auth_key": ("preAuthKey", "PreAuthKey"),
        },
    ),
    "SetApprovedRoutesRequestBody": (
        None,
        {
            "routes": ("routes", None),
        },
    ),
    "SetTagsRequestBody": (
        None,
        {
            "tags": ("tags", None),
        },
    ),
    "User": (
        None,
        {
            "created_at": ("createdAt", None),
            "display_name": ("displayName", None),
            "email": ("email", None),
            "id": ("id", None),
            "name": ("name", None),
            "profile_pic_url": ("profilePicUrl", None),
            "provider": ("provider", None),
            "provider_id": ("providerId", None),
        },
    ),
    "UserOutputBody": (
        None,
        {
            "user": ("user", "User"),
        },
    ),
}


_RESPONSE_ENUM_SCHEMAS: dict[str, object] = {}


def _response_field(field: str, child: str) -> str:
    return f"{field}.{child}" if field else child


def _response_index(field: str, index: int) -> str:
    return f"{field}[{index}]"


def _enum_matches(value: object, candidate: object) -> bool:
    if isinstance(value, bool) or isinstance(candidate, bool):
        return type(value) is type(candidate) and value == candidate
    if isinstance(value, (int, float)) and isinstance(candidate, (int, float)):
        return value == candidate
    return type(value) is type(candidate) and value == candidate


def _validate_response_enum_node(
    value: object,
    schema: object,
    field: str,
    active: set[tuple[int, int]],
) -> None:
    if not isinstance(schema, dict) or value is None:
        return
    reference = schema.get("ref")
    if isinstance(reference, str):
        target = _RESPONSE_ENUM_SCHEMAS.get(reference)
        if target is not None:
            _validate_response_enum_node(value, target, field, active)
        return

    visit = (id(value), id(schema))
    if visit in active:
        return
    active = {*active, visit}

    for member in schema.get("allOf", ()):
        _validate_response_enum_node(value, member, field, active)

    union = schema.get("oneOf") or schema.get("anyOf")
    if isinstance(union, list) and union:
        rejection: SdkValidationError | None = None
        for member in union:
            try:
                _validate_response_enum_node(value, member, field, active)
            except SdkValidationError as error:
                rejection = rejection or error
            else:
                return
        if rejection is not None:
            raise rejection

    properties = schema.get("properties")
    if isinstance(value, dict) and isinstance(properties, dict):
        for name, child_schema in properties.items():
            if name in value:
                _validate_response_enum_node(
                    value[name], child_schema, _response_field(field, name), active
                )

    additional = schema.get("additionalProperties")
    if isinstance(value, dict) and additional is not None:
        known = set(properties) if isinstance(properties, dict) else set()
        for name, child in value.items():
            if name not in known:
                _validate_response_enum_node(
                    child, additional, _response_field(field, name), active
                )

    items = schema.get("items")
    if isinstance(value, list) and items is not None:
        for index, child in enumerate(value):
            _validate_response_enum_node(child, items, _response_index(field, index), active)

    allowed = schema.get("enum")
    if isinstance(allowed, list) and not any(
        _enum_matches(value, candidate) for candidate in allowed
    ):
        raise SdkValidationError(
            field,
            "enum",
            f"Validation failed for '{field}': must be one of {allowed}",
            {"allowed": allowed},
        )


def _validate_response_enums(value: object, type_name: str) -> object:
    """Validates strict response enums against raw wire-shaped payload data."""
    schema = _RESPONSE_ENUM_SCHEMAS.get(type_name)
    if schema is not None:
        _validate_response_enum_node(value, schema, "", set())
    return value


def _plain_to_wire(value: Any) -> Any:
    if value is NOT_GIVEN:
        return NOT_GIVEN
    if isinstance(value, (datetime.datetime, datetime.date, datetime.time)):
        return _wire_scalar(value)
    if isinstance(value, Enum):
        return value.value
    if is_dataclass(value) and not isinstance(value, type):
        model_name = type(value).__name__
        if model_name in _WIRE_SCHEMAS:
            return to_wire(value, model_name)
        return {
            field.name: _plain_to_wire(getattr(value, field.name))
            for field in fields(value)
            if getattr(value, field.name) is not NOT_GIVEN
        }
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        return _plain_to_wire(model_dump(by_alias=True, exclude_unset=True))
    if isinstance(value, dict):
        return {key: _plain_to_wire(item) for key, item in value.items() if item is not NOT_GIVEN}
    if isinstance(value, (list, tuple)):
        return [_plain_to_wire(item) for item in value]
    return value


def _to_wire_nested(value: Any, nested: str | None) -> Any:
    if nested is None:
        return _plain_to_wire(value)
    if isinstance(value, (list, tuple)):
        return [_to_wire_nested(item, nested) for item in value]
    if nested.startswith("map:"):
        value_type = nested[4:]
        return {key: _to_wire_nested(item, value_type) for key, item in value.items()}
    if nested.startswith("union:"):
        members = nested[6:].split("|")
        for member in members:
            cls = _WIRE_SCHEMAS[member][0]
            if cls is not None and isinstance(value, cls):
                return to_wire(value, member)
        if isinstance(value, dict):
            value_keys = set(value)
            member = max(
                members,
                key=lambda name: len(
                    value_keys
                    & (
                        set(_WIRE_SCHEMAS[name][1])
                        | {wire for wire, _nested in _WIRE_SCHEMAS[name][1].values()}
                    )
                ),
            )
            return to_wire(value, member)
        return _plain_to_wire(value)
    return to_wire(value, nested)


def to_wire(value: Any, type_name: str) -> Any:
    """Rewrites a payload's keys from idiomatic names to the spec's wire names,
    recursing into nested models and lists."""
    entry = _WIRE_SCHEMAS.get(type_name)
    if value is None or entry is None:
        return _plain_to_wire(value)
    if isinstance(value, list):
        return [to_wire(item, type_name) for item in value]
    _cls, schema = entry
    out: dict[str, Any] = {}
    for attr, (wire, nested) in schema.items():
        if isinstance(value, dict):
            # Accept values keyed by the idiomatic name or already by the wire
            # name, so callers may pass model instances or wire-shaped dicts.
            raw = value[attr] if attr in value else value.get(wire, _MISSING)
        else:
            raw = getattr(value, attr, _MISSING)
        if raw is _MISSING or raw is NOT_GIVEN:
            continue
        out[wire] = _to_wire_nested(raw, nested)
    return out
