# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from headscale_unofficial_sdk.types import ErrorModel, NodeOutputBody
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


RenameNodeError: TypeAlias = ErrorModel


async def rename_node(
    _client_config: ClientConfig,
    node_id: str,
    new_name: str,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Renames a node by setting its new name. Supply the node identifier and the new name
    in the path.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/rename/{encode_path_segment(new_name)}",
        operation_id="rename_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def rename_node_sync(
    _client_config: ClientConfig,
    node_id: str,
    new_name: str,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Renames a node by setting its new name. Supply the node identifier and the new name
    in the path.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/rename/{encode_path_segment(new_name)}",
        operation_id="rename_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


SetTagsError: TypeAlias = ErrorModel


async def set_tags(
    _client_config: ClientConfig,
    node_id: str,
    tags: list[str] | None | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Sets the tags for a node. Send the tags as an array of strings in the request body.

    Args:
        tags: Optional array value serialized in the `tags` wire field.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/tags",
        json=omit_unset(
            {
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str] | None")),
            }
        ),
        operation_id="set_tags",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def set_tags_sync(
    _client_config: ClientConfig,
    node_id: str,
    tags: list[str] | None | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Sets the tags for a node. Send the tags as an array of strings in the request body.

    Args:
        tags: Optional array value serialized in the `tags` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/tags",
        json=omit_unset(
            {
                "tags": (NOT_GIVEN if tags is NOT_GIVEN else to_wire(tags, "list[str] | None")),
            }
        ),
        operation_id="set_tags",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


__all__ = [
    "RenameNodeError",
    "SetTagsError",
    "rename_node",
    "rename_node_sync",
    "set_tags",
    "set_tags_sync",
]
