# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from headscale_unofficial_sdk.types import (
    BackfillNodeIPsOutputBody,
    DeleteNodeOutputBody,
    ErrorModel,
    ListNodesOutputBody,
    NodeOutputBody,
)
from headscale_unofficial_sdk.validation import validate_date_time
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


DebugCreateNodeError: TypeAlias = ErrorModel


async def debug_create_node(
    _client_config: ClientConfig,
    key: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    routes: list[str] | None | NotGiven = NOT_GIVEN,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Creates a node for debugging purposes. Provide `name` and `user` to describe the
    node, and use `key` or `routes` when those values are needed for the test setup. The
    response contains the created node.

    Args:
        key: Optional `string` value serialized in the `key` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        routes: Optional array value serialized in the `routes` wire field.
        user: Optional `string` value serialized in the `user` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/debug/node",
        json=omit_unset(
            {
                "key": (NOT_GIVEN if key is NOT_GIVEN else to_wire(key, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "routes": (
                    NOT_GIVEN if routes is NOT_GIVEN else to_wire(routes, "list[str] | None")
                ),
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
            }
        ),
        operation_id="debug_create_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def debug_create_node_sync(
    _client_config: ClientConfig,
    key: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    routes: list[str] | None | NotGiven = NOT_GIVEN,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Creates a node for debugging purposes. Provide `name` and `user` to describe the
    node, and use `key` or `routes` when those values are needed for the test setup. The
    response contains the created node.

    Args:
        key: Optional `string` value serialized in the `key` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        routes: Optional array value serialized in the `routes` wire field.
        user: Optional `string` value serialized in the `user` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/debug/node",
        json=omit_unset(
            {
                "key": (NOT_GIVEN if key is NOT_GIVEN else to_wire(key, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "routes": (
                    NOT_GIVEN if routes is NOT_GIVEN else to_wire(routes, "list[str] | None")
                ),
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
            }
        ),
        operation_id="debug_create_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


ListNodesError: TypeAlias = ErrorModel


async def list_nodes(
    _client_config: ClientConfig,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListNodesOutputBody:
    """Lists nodes managed by the service. Supply `user` to filter the results to nodes
    associated with that user; omit it to list nodes without a user filter.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/node",
        params=serialize_query([("user", user, "form", False)]),
        operation_id="list_nodes",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListNodesOutputBody"), ListNodesOutputBody
    )


def list_nodes_sync(
    _client_config: ClientConfig,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListNodesOutputBody:
    """Lists nodes managed by the service. Supply `user` to filter the results to nodes
    associated with that user; omit it to list nodes without a user filter.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/node",
        params=serialize_query([("user", user, "form", False)]),
        operation_id="list_nodes",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListNodesOutputBody"), ListNodesOutputBody
    )


BackfillNodeIpsError: TypeAlias = ErrorModel


async def backfill_node_ips(
    _client_config: ClientConfig,
    confirmed: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BackfillNodeIPsOutputBody:
    """Backfills IP addresses for registered nodes. Use the `confirmed` query parameter to
    indicate whether to confirm the operation, and review the returned `changes` list to
    see what was updated.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/node/backfillips",
        params=serialize_query([("confirmed", confirmed, "form", False)]),
        operation_id="backfill_node_ips",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BackfillNodeIPsOutputBody"), BackfillNodeIPsOutputBody
    )


def backfill_node_ips_sync(
    _client_config: ClientConfig,
    confirmed: bool | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> BackfillNodeIPsOutputBody:
    """Backfills IP addresses for registered nodes. Use the `confirmed` query parameter to
    indicate whether to confirm the operation, and review the returned `changes` list to
    see what was updated.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/node/backfillips",
        params=serialize_query([("confirmed", confirmed, "form", False)]),
        operation_id="backfill_node_ips",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "BackfillNodeIPsOutputBody"), BackfillNodeIPsOutputBody
    )


RegisterNodeError: TypeAlias = ErrorModel


async def register_node(
    _client_config: ClientConfig,
    user: str | NotGiven = NOT_GIVEN,
    key: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Registers a node and returns its node record. Use `user` to associate the node with
    a user and `key` to provide a registration key when needed.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/node/register",
        params=serialize_query([("user", user, "form", False), ("key", key, "form", False)]),
        operation_id="register_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def register_node_sync(
    _client_config: ClientConfig,
    user: str | NotGiven = NOT_GIVEN,
    key: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Registers a node and returns its node record. Use `user` to associate the node with
    a user and `key` to provide a registration key when needed.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/node/register",
        params=serialize_query([("user", user, "form", False), ("key", key, "form", False)]),
        operation_id="register_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


DeleteNodeError: TypeAlias = ErrorModel


async def delete_node(
    _client_config: ClientConfig,
    node_id: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteNodeOutputBody:
    """Deletes a node identified by its ID. Supply `nodeId` as an unsigned 64-bit integer
    value to identify the node to remove.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/node/{encode_path_segment(node_id)}",
        operation_id="delete_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeleteNodeOutputBody)


def delete_node_sync(
    _client_config: ClientConfig,
    node_id: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteNodeOutputBody:
    """Deletes a node identified by its ID. Supply `nodeId` as an unsigned 64-bit integer
    value to identify the node to remove.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/node/{encode_path_segment(node_id)}",
        operation_id="delete_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeleteNodeOutputBody)


GetNodeError: TypeAlias = ErrorModel


async def get_node(
    _client_config: ClientConfig,
    node_id: str,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Retrieves a node by its identifier. Supply `nodeId` as an unsigned 64-bit integer
    value to identify the node.
    """

    _resp = await sdk_request(
        "GET",
        f"/api/v1/node/{encode_path_segment(node_id)}",
        operation_id="get_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def get_node_sync(
    _client_config: ClientConfig,
    node_id: str,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Retrieves a node by its identifier. Supply `nodeId` as an unsigned 64-bit integer
    value to identify the node.
    """

    _resp = sdk_request_sync(
        "GET",
        f"/api/v1/node/{encode_path_segment(node_id)}",
        operation_id="get_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


SetApprovedRoutesError: TypeAlias = ErrorModel


async def set_approved_routes(
    _client_config: ClientConfig,
    node_id: str,
    routes: list[str] | None | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Updates the approved routes for a node. Send the route values in the `routes` array
    to set which routes are approved for that node.

    Args:
        routes: Optional array value serialized in the `routes` wire field.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/approve_routes",
        json=omit_unset(
            {
                "routes": (
                    NOT_GIVEN if routes is NOT_GIVEN else to_wire(routes, "list[str] | None")
                ),
            }
        ),
        operation_id="set_approved_routes",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def set_approved_routes_sync(
    _client_config: ClientConfig,
    node_id: str,
    routes: list[str] | None | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Updates the approved routes for a node. Send the route values in the `routes` array
    to set which routes are approved for that node.

    Args:
        routes: Optional array value serialized in the `routes` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/approve_routes",
        json=omit_unset(
            {
                "routes": (
                    NOT_GIVEN if routes is NOT_GIVEN else to_wire(routes, "list[str] | None")
                ),
            }
        ),
        operation_id="set_approved_routes",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


ExpireNodeError: TypeAlias = ErrorModel


async def expire_node(
    _client_config: ClientConfig,
    node_id: str,
    disable_expiry: bool | NotGiven = NOT_GIVEN,
    expiry: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Updates the expiry settings for a node. Supply `expiry` as an ISO 8601 date-time or
    use `disableExpiry` to specify whether expiry is disabled.

    Args:
        disable_expiry: Optional `boolean` value serialized in the `disableExpiry` wire field.
        expiry: Optional `date-time`-formatted value serialized in the `expiry` wire field.
    """

    if not isinstance(expiry, NotGiven) and expiry is not None:
        validate_date_time("expiry", expiry)

    _resp = await sdk_request(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/expire",
        json=omit_unset(
            {
                "disableExpiry": (
                    NOT_GIVEN if disable_expiry is NOT_GIVEN else to_wire(disable_expiry, "bool")
                ),
                "expiry": (
                    NOT_GIVEN if expiry is NOT_GIVEN else to_wire(expiry, "datetime.datetime")
                ),
            }
        ),
        operation_id="expire_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


def expire_node_sync(
    _client_config: ClientConfig,
    node_id: str,
    disable_expiry: bool | NotGiven = NOT_GIVEN,
    expiry: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> NodeOutputBody:
    """Updates the expiry settings for a node. Supply `expiry` as an ISO 8601 date-time or
    use `disableExpiry` to specify whether expiry is disabled.

    Args:
        disable_expiry: Optional `boolean` value serialized in the `disableExpiry` wire field.
        expiry: Optional `date-time`-formatted value serialized in the `expiry` wire field.
    """

    if not isinstance(expiry, NotGiven) and expiry is not None:
        validate_date_time("expiry", expiry)

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/node/{encode_path_segment(node_id)}/expire",
        json=omit_unset(
            {
                "disableExpiry": (
                    NOT_GIVEN if disable_expiry is NOT_GIVEN else to_wire(disable_expiry, "bool")
                ),
                "expiry": (
                    NOT_GIVEN if expiry is NOT_GIVEN else to_wire(expiry, "datetime.datetime")
                ),
            }
        ),
        operation_id="expire_node",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "NodeOutputBody"), NodeOutputBody
    )


__all__ = [
    "BackfillNodeIpsError",
    "DebugCreateNodeError",
    "DeleteNodeError",
    "ExpireNodeError",
    "GetNodeError",
    "ListNodesError",
    "RegisterNodeError",
    "SetApprovedRoutesError",
    "backfill_node_ips",
    "backfill_node_ips_sync",
    "debug_create_node",
    "debug_create_node_sync",
    "delete_node",
    "delete_node_sync",
    "expire_node",
    "expire_node_sync",
    "get_node",
    "get_node_sync",
    "list_nodes",
    "list_nodes_sync",
    "register_node",
    "register_node_sync",
    "set_approved_routes",
    "set_approved_routes_sync",
]
