# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from headscale_unofficial_sdk.types import (
    CreateApiKeyOutputBody,
    DeleteApiKeyOutputBody,
    ErrorModel,
    ExpireApiKeyOutputBody,
    ListApiKeysOutputBody,
)
from headscale_unofficial_sdk.validation import validate_date_time
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


ListApiKeysError: TypeAlias = ErrorModel


async def list_api_keys(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ListApiKeysOutputBody:
    """Lists the API keys available to the authenticated user. Review each key's
    identifier, prefix, expiration, creation time, and last-seen time to manage existing
    credentials.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/apikey",
        operation_id="list_api_keys",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListApiKeysOutputBody"), ListApiKeysOutputBody
    )


def list_api_keys_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ListApiKeysOutputBody:
    """Lists the API keys available to the authenticated user. Review each key's
    identifier, prefix, expiration, creation time, and last-seen time to manage existing
    credentials.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/apikey",
        operation_id="list_api_keys",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListApiKeysOutputBody"), ListApiKeysOutputBody
    )


CreateApiKeyError: TypeAlias = ErrorModel


async def create_api_key(
    _client_config: ClientConfig,
    expiration: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateApiKeyOutputBody:
    """Creates a new API key. You can provide `expiration` as a date-time value or omit it
    if you do not want to specify an expiration. The response contains the generated key
    in `apiKey`.

    Args:
        expiration: Optional `date-time`-formatted value serialized in the `expiration` wire field.
    """

    if not isinstance(expiration, NotGiven) and expiration is not None:
        validate_date_time("expiration", expiration)

    _resp = await sdk_request(
        "POST",
        "/api/v1/apikey",
        json=omit_unset(
            {
                "expiration": (
                    NOT_GIVEN
                    if expiration is NOT_GIVEN
                    else to_wire(expiration, "datetime.datetime")
                ),
            }
        ),
        operation_id="create_api_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateApiKeyOutputBody"), CreateApiKeyOutputBody
    )


def create_api_key_sync(
    _client_config: ClientConfig,
    expiration: datetime.datetime | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CreateApiKeyOutputBody:
    """Creates a new API key. You can provide `expiration` as a date-time value or omit it
    if you do not want to specify an expiration. The response contains the generated key
    in `apiKey`.

    Args:
        expiration: Optional `date-time`-formatted value serialized in the `expiration` wire field.
    """

    if not isinstance(expiration, NotGiven) and expiration is not None:
        validate_date_time("expiration", expiration)

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/apikey",
        json=omit_unset(
            {
                "expiration": (
                    NOT_GIVEN
                    if expiration is NOT_GIVEN
                    else to_wire(expiration, "datetime.datetime")
                ),
            }
        ),
        operation_id="create_api_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "CreateApiKeyOutputBody"), CreateApiKeyOutputBody
    )


ExpireApiKeyError: TypeAlias = ErrorModel


async def expire_api_key(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    prefix: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ExpireApiKeyOutputBody:
    """Expires an API key. Identify the key using `id`, `prefix`, or both, according to the
    key details available to you. The response confirms the operation with an empty
    object.

    Args:
        id: Optional `uint64`-formatted value serialized in the `id` wire field.
        prefix: Optional `string` value serialized in the `prefix` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/apikey/expire",
        json=omit_unset(
            {
                "id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "str")),
                "prefix": (NOT_GIVEN if prefix is NOT_GIVEN else to_wire(prefix, "str")),
            }
        ),
        operation_id="expire_api_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, ExpireApiKeyOutputBody)


def expire_api_key_sync(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    prefix: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ExpireApiKeyOutputBody:
    """Expires an API key. Identify the key using `id`, `prefix`, or both, according to the
    key details available to you. The response confirms the operation with an empty
    object.

    Args:
        id: Optional `uint64`-formatted value serialized in the `id` wire field.
        prefix: Optional `string` value serialized in the `prefix` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/apikey/expire",
        json=omit_unset(
            {
                "id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "str")),
                "prefix": (NOT_GIVEN if prefix is NOT_GIVEN else to_wire(prefix, "str")),
            }
        ),
        operation_id="expire_api_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, ExpireApiKeyOutputBody)


DeleteApiKeyError: TypeAlias = ErrorModel


async def delete_api_key(
    _client_config: ClientConfig,
    prefix: str,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteApiKeyOutputBody:
    """Deletes an API key selected by its prefix. You can also supply `id` as a
    uint64-formatted string to further identify the key. The response confirms the
    operation with an empty object.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/apikey/{encode_path_segment(prefix)}",
        params=serialize_query([("id", id, "form", False)]),
        operation_id="delete_api_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeleteApiKeyOutputBody)


def delete_api_key_sync(
    _client_config: ClientConfig,
    prefix: str,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteApiKeyOutputBody:
    """Deletes an API key selected by its prefix. You can also supply `id` as a
    uint64-formatted string to further identify the key. The response confirms the
    operation with an empty object.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/apikey/{encode_path_segment(prefix)}",
        params=serialize_query([("id", id, "form", False)]),
        operation_id="delete_api_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeleteApiKeyOutputBody)


__all__ = [
    "CreateApiKeyError",
    "DeleteApiKeyError",
    "ExpireApiKeyError",
    "ListApiKeysError",
    "create_api_key",
    "create_api_key_sync",
    "delete_api_key",
    "delete_api_key_sync",
    "expire_api_key",
    "expire_api_key_sync",
    "list_api_keys",
    "list_api_keys_sync",
]
