# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from headscale_unofficial_sdk.types import (
    AuthApproveOutputBody,
    AuthRegisterOutputBody,
    AuthRejectOutputBody,
    ErrorModel,
)
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


AuthApproveError: TypeAlias = ErrorModel


async def auth_approve(
    _client_config: ClientConfig,
    auth_id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AuthApproveOutputBody:
    """Approves a pending authentication session. Supply the session's `authId` to identify
    the request you want to approve. The response confirms the operation with an empty
    object.

    Args:
        auth_id: Optional `string` value serialized in the `authId` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/auth/approve",
        json=omit_unset(
            {
                "authId": (NOT_GIVEN if auth_id is NOT_GIVEN else to_wire(auth_id, "str")),
            }
        ),
        operation_id="auth_approve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, AuthApproveOutputBody)


def auth_approve_sync(
    _client_config: ClientConfig,
    auth_id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AuthApproveOutputBody:
    """Approves a pending authentication session. Supply the session's `authId` to identify
    the request you want to approve. The response confirms the operation with an empty
    object.

    Args:
        auth_id: Optional `string` value serialized in the `authId` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/auth/approve",
        json=omit_unset(
            {
                "authId": (NOT_GIVEN if auth_id is NOT_GIVEN else to_wire(auth_id, "str")),
            }
        ),
        operation_id="auth_approve",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, AuthApproveOutputBody)


AuthRegisterError: TypeAlias = ErrorModel


async def auth_register(
    _client_config: ClientConfig,
    auth_id: str | NotGiven = NOT_GIVEN,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AuthRegisterOutputBody:
    """Registers a node through the authentication flow. Use `authId` to associate the
    registration with an authentication session and `user` to specify the user for the
    node. The response contains the registered node.

    Args:
        auth_id: Optional `string` value serialized in the `authId` wire field.
        user: Optional `string` value serialized in the `user` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/auth/register",
        json=omit_unset(
            {
                "authId": (NOT_GIVEN if auth_id is NOT_GIVEN else to_wire(auth_id, "str")),
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
            }
        ),
        operation_id="auth_register",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "AuthRegisterOutputBody"), AuthRegisterOutputBody
    )


def auth_register_sync(
    _client_config: ClientConfig,
    auth_id: str | NotGiven = NOT_GIVEN,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AuthRegisterOutputBody:
    """Registers a node through the authentication flow. Use `authId` to associate the
    registration with an authentication session and `user` to specify the user for the
    node. The response contains the registered node.

    Args:
        auth_id: Optional `string` value serialized in the `authId` wire field.
        user: Optional `string` value serialized in the `user` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/auth/register",
        json=omit_unset(
            {
                "authId": (NOT_GIVEN if auth_id is NOT_GIVEN else to_wire(auth_id, "str")),
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
            }
        ),
        operation_id="auth_register",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "AuthRegisterOutputBody"), AuthRegisterOutputBody
    )


AuthRejectError: TypeAlias = ErrorModel


async def auth_reject(
    _client_config: ClientConfig,
    auth_id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AuthRejectOutputBody:
    """Rejects a pending authentication session. Supply the session's `authId` to identify
    the request you want to reject. The response confirms the operation with an empty
    object.

    Args:
        auth_id: Optional `string` value serialized in the `authId` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/auth/reject",
        json=omit_unset(
            {
                "authId": (NOT_GIVEN if auth_id is NOT_GIVEN else to_wire(auth_id, "str")),
            }
        ),
        operation_id="auth_reject",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, AuthRejectOutputBody)


def auth_reject_sync(
    _client_config: ClientConfig,
    auth_id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> AuthRejectOutputBody:
    """Rejects a pending authentication session. Supply the session's `authId` to identify
    the request you want to reject. The response confirms the operation with an empty
    object.

    Args:
        auth_id: Optional `string` value serialized in the `authId` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/auth/reject",
        json=omit_unset(
            {
                "authId": (NOT_GIVEN if auth_id is NOT_GIVEN else to_wire(auth_id, "str")),
            }
        ),
        operation_id="auth_reject",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, AuthRejectOutputBody)


__all__ = [
    "AuthApproveError",
    "AuthRegisterError",
    "AuthRejectError",
    "auth_approve",
    "auth_approve_sync",
    "auth_register",
    "auth_register_sync",
    "auth_reject",
    "auth_reject_sync",
]
