# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    ClientConfig,
    RequestOptions,
    sdk_request,
    sdk_request_sync,
)
from headscale_unofficial_sdk.types import ErrorModel, HealthResponseBody
from headscale_unofficial_sdk.wire import _validate_response_enums


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


HealthError: TypeAlias = ErrorModel


async def health(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> HealthResponseBody:
    """Reports the server's health, including database connectivity. Read
    `databaseConnectivity` to determine whether the database connection is available.

    Reports server health, including database connectivity.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/health",
        operation_id="health",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "HealthResponseBody"), HealthResponseBody
    )


def health_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> HealthResponseBody:
    """Reports the server's health, including database connectivity. Read
    `databaseConnectivity` to determine whether the database connection is available.

    Reports server health, including database connectivity.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/health",
        operation_id="health",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "HealthResponseBody"), HealthResponseBody
    )


__all__ = [
    "HealthError",
    "health",
    "health_sync",
]
