# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
)
from headscale_unofficial_sdk.types import CheckPolicyOutputBody, ErrorModel, PolicyResponseBody
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


GetPolicyError: TypeAlias = ErrorModel


async def get_policy(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> PolicyResponseBody:
    """Retrieves the current policy. The response includes the policy text and the time it
    was last updated.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/policy",
        operation_id="get_policy",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PolicyResponseBody"), PolicyResponseBody
    )


def get_policy_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> PolicyResponseBody:
    """Retrieves the current policy. The response includes the policy text and the time it
    was last updated.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/policy",
        operation_id="get_policy",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PolicyResponseBody"), PolicyResponseBody
    )


SetPolicyError: TypeAlias = ErrorModel


async def set_policy(
    _client_config: ClientConfig,
    policy: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PolicyResponseBody:
    """Replaces the current policy with the policy value supplied in the request body.
    Include the policy text in `policy`; the response provides the saved policy and its
    update time.

    Args:
        policy: Optional `string` value serialized in the `policy` wire field.
    """

    _resp = await sdk_request(
        "PUT",
        "/api/v1/policy",
        json=omit_unset(
            {
                "policy": (NOT_GIVEN if policy is NOT_GIVEN else to_wire(policy, "str")),
            }
        ),
        operation_id="set_policy",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PolicyResponseBody"), PolicyResponseBody
    )


def set_policy_sync(
    _client_config: ClientConfig,
    policy: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PolicyResponseBody:
    """Replaces the current policy with the policy value supplied in the request body.
    Include the policy text in `policy`; the response provides the saved policy and its
    update time.

    Args:
        policy: Optional `string` value serialized in the `policy` wire field.
    """

    _resp = sdk_request_sync(
        "PUT",
        "/api/v1/policy",
        json=omit_unset(
            {
                "policy": (NOT_GIVEN if policy is NOT_GIVEN else to_wire(policy, "str")),
            }
        ),
        operation_id="set_policy",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PolicyResponseBody"), PolicyResponseBody
    )


CheckPolicyError: TypeAlias = ErrorModel


async def check_policy(
    _client_config: ClientConfig,
    policy: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CheckPolicyOutputBody:
    """Validates a policy against the server's live users and nodes without saving it.
    Provide `policy` as a string when included; the request body is required.

    Validates the given policy against the server's live users and nodes without
    persisting it.

    Args:
        policy: Optional `string` value serialized in the `policy` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/policy/check",
        json=omit_unset(
            {
                "policy": (NOT_GIVEN if policy is NOT_GIVEN else to_wire(policy, "str")),
            }
        ),
        operation_id="check_policy",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, CheckPolicyOutputBody)


def check_policy_sync(
    _client_config: ClientConfig,
    policy: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> CheckPolicyOutputBody:
    """Validates a policy against the server's live users and nodes without saving it.
    Provide `policy` as a string when included; the request body is required.

    Validates the given policy against the server's live users and nodes without
    persisting it.

    Args:
        policy: Optional `string` value serialized in the `policy` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/policy/check",
        json=omit_unset(
            {
                "policy": (NOT_GIVEN if policy is NOT_GIVEN else to_wire(policy, "str")),
            }
        ),
        operation_id="check_policy",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, CheckPolicyOutputBody)


__all__ = [
    "CheckPolicyError",
    "GetPolicyError",
    "SetPolicyError",
    "check_policy",
    "check_policy_sync",
    "get_policy",
    "get_policy_sync",
    "set_policy",
    "set_policy_sync",
]
