# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from headscale_unofficial_sdk.types import (
    DeletePreAuthKeyOutputBody,
    ErrorModel,
    ExpirePreAuthKeyOutputBody,
    ListPreAuthKeysOutputBody,
    PreAuthKeyOutputBody,
)
from headscale_unofficial_sdk.validation import validate_date_time
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


DeletePreAuthKeyError: TypeAlias = ErrorModel


async def delete_pre_auth_key(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeletePreAuthKeyOutputBody:
    """Deletes a pre-auth key. Use the optional `id` query parameter to identify the key to
    delete; provide it as a uint64-formatted string when supplied.
    """

    _resp = await sdk_request(
        "DELETE",
        "/api/v1/preauthkey",
        params=serialize_query([("id", id, "form", False)]),
        operation_id="delete_pre_auth_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeletePreAuthKeyOutputBody)


def delete_pre_auth_key_sync(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> DeletePreAuthKeyOutputBody:
    """Deletes a pre-auth key. Use the optional `id` query parameter to identify the key to
    delete; provide it as a uint64-formatted string when supplied.
    """

    _resp = sdk_request_sync(
        "DELETE",
        "/api/v1/preauthkey",
        params=serialize_query([("id", id, "form", False)]),
        operation_id="delete_pre_auth_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeletePreAuthKeyOutputBody)


ListPreAuthKeysError: TypeAlias = ErrorModel


async def list_pre_auth_keys(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ListPreAuthKeysOutputBody:
    """Lists the pre-auth keys configured on the server. Use this operation to retrieve
    each key's user, key value, expiration, usage state, and ACL tags.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/preauthkey",
        operation_id="list_pre_auth_keys",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListPreAuthKeysOutputBody"), ListPreAuthKeysOutputBody
    )


def list_pre_auth_keys_sync(
    _client_config: ClientConfig,
    *,
    request_options: RequestOptions | None = None,
) -> ListPreAuthKeysOutputBody:
    """Lists the pre-auth keys configured on the server. Use this operation to retrieve
    each key's user, key value, expiration, usage state, and ACL tags.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/preauthkey",
        operation_id="list_pre_auth_keys",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListPreAuthKeysOutputBody"), ListPreAuthKeysOutputBody
    )


CreatePreAuthKeyError: TypeAlias = ErrorModel


async def create_pre_auth_key(
    _client_config: ClientConfig,
    acl_tags: list[str] | None | NotGiven = NOT_GIVEN,
    ephemeral: bool | NotGiven = NOT_GIVEN,
    expiration: datetime.datetime | NotGiven = NOT_GIVEN,
    reusable: bool | NotGiven = NOT_GIVEN,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PreAuthKeyOutputBody:
    """Creates a pre-auth key for a user. Configure the key with fields such as `user`,
    `expiration`, `reusable`, `ephemeral`, and `aclTags`; `user` is a uint64-formatted
    string and `expiration` is a date-time.

    Args:
        acl_tags: Optional array value serialized in the `aclTags` wire field.
        ephemeral: Optional `boolean` value serialized in the `ephemeral` wire field.
        expiration: Optional `date-time`-formatted value serialized in the `expiration` wire field.
        reusable: Optional `boolean` value serialized in the `reusable` wire field.
        user: Optional `uint64`-formatted value serialized in the `user` wire field.
    """

    if not isinstance(expiration, NotGiven) and expiration is not None:
        validate_date_time("expiration", expiration)

    _resp = await sdk_request(
        "POST",
        "/api/v1/preauthkey",
        json=omit_unset(
            {
                "aclTags": (
                    NOT_GIVEN if acl_tags is NOT_GIVEN else to_wire(acl_tags, "list[str] | None")
                ),
                "ephemeral": (NOT_GIVEN if ephemeral is NOT_GIVEN else to_wire(ephemeral, "bool")),
                "expiration": (
                    NOT_GIVEN
                    if expiration is NOT_GIVEN
                    else to_wire(expiration, "datetime.datetime")
                ),
                "reusable": (NOT_GIVEN if reusable is NOT_GIVEN else to_wire(reusable, "bool")),
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
            }
        ),
        operation_id="create_pre_auth_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PreAuthKeyOutputBody"), PreAuthKeyOutputBody
    )


def create_pre_auth_key_sync(
    _client_config: ClientConfig,
    acl_tags: list[str] | None | NotGiven = NOT_GIVEN,
    ephemeral: bool | NotGiven = NOT_GIVEN,
    expiration: datetime.datetime | NotGiven = NOT_GIVEN,
    reusable: bool | NotGiven = NOT_GIVEN,
    user: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> PreAuthKeyOutputBody:
    """Creates a pre-auth key for a user. Configure the key with fields such as `user`,
    `expiration`, `reusable`, `ephemeral`, and `aclTags`; `user` is a uint64-formatted
    string and `expiration` is a date-time.

    Args:
        acl_tags: Optional array value serialized in the `aclTags` wire field.
        ephemeral: Optional `boolean` value serialized in the `ephemeral` wire field.
        expiration: Optional `date-time`-formatted value serialized in the `expiration` wire field.
        reusable: Optional `boolean` value serialized in the `reusable` wire field.
        user: Optional `uint64`-formatted value serialized in the `user` wire field.
    """

    if not isinstance(expiration, NotGiven) and expiration is not None:
        validate_date_time("expiration", expiration)

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/preauthkey",
        json=omit_unset(
            {
                "aclTags": (
                    NOT_GIVEN if acl_tags is NOT_GIVEN else to_wire(acl_tags, "list[str] | None")
                ),
                "ephemeral": (NOT_GIVEN if ephemeral is NOT_GIVEN else to_wire(ephemeral, "bool")),
                "expiration": (
                    NOT_GIVEN
                    if expiration is NOT_GIVEN
                    else to_wire(expiration, "datetime.datetime")
                ),
                "reusable": (NOT_GIVEN if reusable is NOT_GIVEN else to_wire(reusable, "bool")),
                "user": (NOT_GIVEN if user is NOT_GIVEN else to_wire(user, "str")),
            }
        ),
        operation_id="create_pre_auth_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "PreAuthKeyOutputBody"), PreAuthKeyOutputBody
    )


ExpirePreAuthKeyError: TypeAlias = ErrorModel


async def expire_pre_auth_key(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ExpirePreAuthKeyOutputBody:
    """Expires a pre-auth key. Supply its identifier in the `id` field as a
    uint64-formatted string when specifying which key to expire.

    Args:
        id: Optional `uint64`-formatted value serialized in the `id` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/preauthkey/expire",
        json=omit_unset({"id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "str"))}),
        operation_id="expire_pre_auth_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, ExpirePreAuthKeyOutputBody)


def expire_pre_auth_key_sync(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ExpirePreAuthKeyOutputBody:
    """Expires a pre-auth key. Supply its identifier in the `id` field as a
    uint64-formatted string when specifying which key to expire.

    Args:
        id: Optional `uint64`-formatted value serialized in the `id` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/preauthkey/expire",
        json=omit_unset({"id": (NOT_GIVEN if id is NOT_GIVEN else to_wire(id, "str"))}),
        operation_id="expire_pre_auth_key",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, ExpirePreAuthKeyOutputBody)


__all__ = [
    "CreatePreAuthKeyError",
    "DeletePreAuthKeyError",
    "ExpirePreAuthKeyError",
    "ListPreAuthKeysError",
    "create_pre_auth_key",
    "create_pre_auth_key_sync",
    "delete_pre_auth_key",
    "delete_pre_auth_key_sync",
    "expire_pre_auth_key",
    "expire_pre_auth_key_sync",
    "list_pre_auth_keys",
    "list_pre_auth_keys_sync",
]
