# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any, TypeAlias

from pydantic import TypeAdapter

import headscale_unofficial_sdk.types as _response_types
from headscale_unofficial_sdk.client import (
    NOT_GIVEN,
    ClientConfig,
    NotGiven,
    RequestOptions,
    encode_path_segment,
    omit_unset,
    sdk_request,
    sdk_request_sync,
    serialize_query,
)
from headscale_unofficial_sdk.types import (
    DeleteUserOutputBody,
    ErrorModel,
    ListUsersOutputBody,
    UserOutputBody,
)
from headscale_unofficial_sdk.wire import _validate_response_enums, to_wire


def _validate_pydantic_response(value: Any, response_type: Any) -> Any:
    adapter = TypeAdapter(response_type)
    if not adapter.pydantic_complete:
        adapter.rebuild(_types_namespace=vars(_response_types))
    return adapter.validate_python(value)


ListUsersError: TypeAlias = ErrorModel


async def list_users(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUsersOutputBody:
    """Lists users, with optional filters for user identifier, name, or email. Supply `id`
    as a uint64-formatted string when filtering by identifier; `name` and `email` are
    string filters.
    """

    _resp = await sdk_request(
        "GET",
        "/api/v1/user",
        params=serialize_query(
            [
                ("id", id, "form", False),
                ("name", name, "form", False),
                ("email", email, "form", False),
            ]
        ),
        operation_id="list_users",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUsersOutputBody"), ListUsersOutputBody
    )


def list_users_sync(
    _client_config: ClientConfig,
    id: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> ListUsersOutputBody:
    """Lists users, with optional filters for user identifier, name, or email. Supply `id`
    as a uint64-formatted string when filtering by identifier; `name` and `email` are
    string filters.
    """

    _resp = sdk_request_sync(
        "GET",
        "/api/v1/user",
        params=serialize_query(
            [
                ("id", id, "form", False),
                ("name", name, "form", False),
                ("email", email, "form", False),
            ]
        ),
        operation_id="list_users",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "ListUsersOutputBody"), ListUsersOutputBody
    )


CreateUserError: TypeAlias = ErrorModel


async def create_user(
    _client_config: ClientConfig,
    display_name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    picture_url: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserOutputBody:
    """Creates a user record. You can provide `name`, `displayName`, `email`, and
    `pictureUrl`; all defined fields are strings and none is marked as required.

    Args:
        display_name: Optional `string` value serialized in the `displayName` wire field.
        email: Optional `string` value serialized in the `email` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        picture_url: Optional `string` value serialized in the `pictureUrl` wire field.
    """

    _resp = await sdk_request(
        "POST",
        "/api/v1/user",
        json=omit_unset(
            {
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "pictureUrl": (
                    NOT_GIVEN if picture_url is NOT_GIVEN else to_wire(picture_url, "str")
                ),
            }
        ),
        operation_id="create_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserOutputBody"), UserOutputBody
    )


def create_user_sync(
    _client_config: ClientConfig,
    display_name: str | NotGiven = NOT_GIVEN,
    email: str | NotGiven = NOT_GIVEN,
    name: str | NotGiven = NOT_GIVEN,
    picture_url: str | NotGiven = NOT_GIVEN,
    *,
    request_options: RequestOptions | None = None,
) -> UserOutputBody:
    """Creates a user record. You can provide `name`, `displayName`, `email`, and
    `pictureUrl`; all defined fields are strings and none is marked as required.

    Args:
        display_name: Optional `string` value serialized in the `displayName` wire field.
        email: Optional `string` value serialized in the `email` wire field.
        name: Optional `string` value serialized in the `name` wire field.
        picture_url: Optional `string` value serialized in the `pictureUrl` wire field.
    """

    _resp = sdk_request_sync(
        "POST",
        "/api/v1/user",
        json=omit_unset(
            {
                "displayName": (
                    NOT_GIVEN if display_name is NOT_GIVEN else to_wire(display_name, "str")
                ),
                "email": (NOT_GIVEN if email is NOT_GIVEN else to_wire(email, "str")),
                "name": (NOT_GIVEN if name is NOT_GIVEN else to_wire(name, "str")),
                "pictureUrl": (
                    NOT_GIVEN if picture_url is NOT_GIVEN else to_wire(picture_url, "str")
                ),
            }
        ),
        operation_id="create_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserOutputBody"), UserOutputBody
    )


DeleteUserError: TypeAlias = ErrorModel


async def delete_user(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteUserOutputBody:
    """Deletes a user by identifier. Provide the user's `id` as a uint64-formatted string
    in the path.
    """

    _resp = await sdk_request(
        "DELETE",
        f"/api/v1/user/{encode_path_segment(id)}",
        operation_id="delete_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeleteUserOutputBody)


def delete_user_sync(
    _client_config: ClientConfig,
    id: str,
    *,
    request_options: RequestOptions | None = None,
) -> DeleteUserOutputBody:
    """Deletes a user by identifier. Provide the user's `id` as a uint64-formatted string
    in the path.
    """

    _resp = sdk_request_sync(
        "DELETE",
        f"/api/v1/user/{encode_path_segment(id)}",
        operation_id="delete_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(_resp.data, DeleteUserOutputBody)


RenameUserError: TypeAlias = ErrorModel


async def rename_user(
    _client_config: ClientConfig,
    old_id: str,
    new_name: str,
    *,
    request_options: RequestOptions | None = None,
) -> UserOutputBody:
    """Renames a user by changing the name associated with the specified identifier.
    Provide `oldId` as a uint64-formatted string and `newName` as a string in the path.
    """

    _resp = await sdk_request(
        "POST",
        f"/api/v1/user/{encode_path_segment(old_id)}/rename/{encode_path_segment(new_name)}",
        operation_id="rename_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserOutputBody"), UserOutputBody
    )


def rename_user_sync(
    _client_config: ClientConfig,
    old_id: str,
    new_name: str,
    *,
    request_options: RequestOptions | None = None,
) -> UserOutputBody:
    """Renames a user by changing the name associated with the specified identifier.
    Provide `oldId` as a uint64-formatted string and `newName` as a string in the path.
    """

    _resp = sdk_request_sync(
        "POST",
        f"/api/v1/user/{encode_path_segment(old_id)}/rename/{encode_path_segment(new_name)}",
        operation_id="rename_user",
        response_decoder="json",
        request_options=request_options,
        config=_client_config,
    )
    return _validate_pydantic_response(
        _validate_response_enums(_resp.data, "UserOutputBody"), UserOutputBody
    )


__all__ = [
    "CreateUserError",
    "DeleteUserError",
    "ListUsersError",
    "RenameUserError",
    "create_user",
    "create_user_sync",
    "delete_user",
    "delete_user_sync",
    "list_users",
    "list_users_sync",
    "rename_user",
    "rename_user_sync",
]
