# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_date_time, validate_required


class ApiKey(BaseModel):
    """Typed representation of the `ApiKey` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    created_at: datetime.datetime | None = Field(alias="createdAt")
    """Required `date-time`-formatted value serialized in the `createdAt` wire field."""
    expiration: datetime.datetime | None
    """Required `date-time`-formatted value serialized in the `expiration` wire field."""
    id: str
    """Required `uint64`-formatted value serialized in the `id` wire field."""
    last_seen: datetime.datetime | None = Field(alias="lastSeen")
    """Required `date-time`-formatted value serialized in the `lastSeen` wire field."""
    prefix: str
    """Required `string` value serialized in the `prefix` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            ["id", "prefix", "expiration", "createdAt", "lastSeen"],
            {"createdAt": "created_at", "lastSeen": "last_seen"},
        )
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def _validate_created_at(cls, value):
        if value is not None:
            validate_date_time("createdAt", value)
        return value

    @field_validator("expiration", mode="before")
    @classmethod
    def _validate_expiration(cls, value):
        if value is not None:
            validate_date_time("expiration", value)
        return value

    @field_validator("last_seen", mode="before")
    @classmethod
    def _validate_last_seen(cls, value):
        if value is not None:
            validate_date_time("lastSeen", value)
        return value


class CreateApiKeyOutputBody(BaseModel):
    """Typed representation of the `CreateApiKeyOutputBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    api_key: str = Field(alias="apiKey")
    """Required `string` value serialized in the `apiKey` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["apiKey"], {"apiKey": "api_key"})
        return value


class CreateApiKeyRequestBody(BaseModel):
    """Typed representation of the `CreateApiKeyRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    expiration: datetime.datetime | NotGiven = NOT_GIVEN
    """Optional `date-time`-formatted value serialized in the `expiration` wire field."""

    @field_validator("expiration", mode="before")
    @classmethod
    def _validate_expiration(cls, value):
        validate_date_time("expiration", value)
        return value


class DeleteApiKeyOutputBody(BaseModel):
    """Typed representation of the `DeleteApiKeyOutputBody` API schema."""


class ExpireApiKeyOutputBody(BaseModel):
    """Typed representation of the `ExpireApiKeyOutputBody` API schema."""


class ExpireApiKeyRequestBody(BaseModel):
    """Typed representation of the `ExpireApiKeyRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: str | NotGiven = NOT_GIVEN
    """Optional `uint64`-formatted value serialized in the `id` wire field."""
    prefix: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `prefix` wire field."""


class ListApiKeysOutputBody(BaseModel):
    """Typed representation of the `ListApiKeysOutputBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    api_keys: list[ApiKey] = Field(alias="apiKeys")
    """Required array value serialized in the `apiKeys` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["apiKeys"], {"apiKeys": "api_keys"})
        return value
