# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven
from headscale_unofficial_sdk.types.shared import Node

from ..validation import validate_required


class AuthApproveOutputBody(BaseModel):
    """Typed representation of the `AuthApproveOutputBody` API schema."""


class AuthApproveRequestBody(BaseModel):
    """Typed representation of the `AuthApproveRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    auth_id: str | NotGiven = Field(NOT_GIVEN, alias="authId")
    """Optional `string` value serialized in the `authId` wire field."""


class AuthRegisterOutputBody(BaseModel):
    """Typed representation of the `AuthRegisterOutputBody` API schema."""

    node: Node
    """Required object value serialized in the `node` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["node"])
        return value


class AuthRegisterRequestBody(BaseModel):
    """Typed representation of the `AuthRegisterRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    auth_id: str | NotGiven = Field(NOT_GIVEN, alias="authId")
    """Optional `string` value serialized in the `authId` wire field."""
    user: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user` wire field."""


class AuthRejectOutputBody(BaseModel):
    """Typed representation of the `AuthRejectOutputBody` API schema."""


class AuthRejectRequestBody(BaseModel):
    """Typed representation of the `AuthRejectRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    auth_id: str | NotGiven = Field(NOT_GIVEN, alias="authId")
    """Optional `string` value serialized in the `authId` wire field."""
