# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from ..validation import validate_required


class HealthResponseBody(BaseModel):
    """Typed representation of the `HealthResponseBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    database_connectivity: bool = Field(alias="databaseConnectivity")
    """Required `boolean` value serialized in the `databaseConnectivity` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value, ["databaseConnectivity"], {"databaseConnectivity": "database_connectivity"}
        )
        return value
