# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven
from headscale_unofficial_sdk.types.shared import Node

from ..validation import validate_date_time, validate_required


class BackfillNodeIPsOutputBody(BaseModel):
    """Typed representation of the `BackfillNodeIPsOutputBody` API schema."""

    changes: list[str]
    """Required array value serialized in the `changes` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["changes"])
        return value


class DebugCreateNodeRequestBody(BaseModel):
    """Typed representation of the `DebugCreateNodeRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    key: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `key` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    routes: list[str] | None | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `routes` wire field."""
    user: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `user` wire field."""


class DeleteNodeOutputBody(BaseModel):
    """Typed representation of the `DeleteNodeOutputBody` API schema."""


class ExpireNodeRequestBody(BaseModel):
    """Typed representation of the `ExpireNodeRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    disable_expiry: bool | NotGiven = Field(NOT_GIVEN, alias="disableExpiry")
    """Optional `boolean` value serialized in the `disableExpiry` wire field."""
    expiry: datetime.datetime | NotGiven = NOT_GIVEN
    """Optional `date-time`-formatted value serialized in the `expiry` wire field."""

    @field_validator("expiry", mode="before")
    @classmethod
    def _validate_expiry(cls, value):
        validate_date_time("expiry", value)
        return value


class ListNodesOutputBody(BaseModel):
    """Typed representation of the `ListNodesOutputBody` API schema."""

    nodes: list[Node]
    """Required array value serialized in the `nodes` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["nodes"])
        return value


class NodeOutputBody(BaseModel):
    """Typed representation of the `NodeOutputBody` API schema."""

    node: Node
    """Required object value serialized in the `node` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["node"])
        return value


class SetApprovedRoutesRequestBody(BaseModel):
    """Typed representation of the `SetApprovedRoutesRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    routes: list[str] | None | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `routes` wire field."""


class SetTagsRequestBody(BaseModel):
    """Typed representation of the `SetTagsRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    tags: list[str] | None | NotGiven = NOT_GIVEN
    """Optional array value serialized in the `tags` wire field."""
