# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_date_time, validate_required


class CheckPolicyOutputBody(BaseModel):
    """Typed representation of the `CheckPolicyOutputBody` API schema."""


class PolicyRequestBody(BaseModel):
    """Typed representation of the `PolicyRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    policy: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `policy` wire field."""


class PolicyResponseBody(BaseModel):
    """Typed representation of the `PolicyResponseBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    policy: str
    """Required `string` value serialized in the `policy` wire field."""
    updated_at: datetime.datetime = Field(alias="updatedAt")
    """Required `date-time`-formatted value serialized in the `updatedAt` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["policy", "updatedAt"], {"updatedAt": "updated_at"})
        return value

    @field_validator("updated_at", mode="before")
    @classmethod
    def _validate_updated_at(cls, value):
        validate_date_time("updatedAt", value)
        return value
