# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven
from headscale_unofficial_sdk.types.shared import User

from ..validation import validate_date_time, validate_required


class CreatePreAuthKeyRequestBody(BaseModel):
    """Typed representation of the `CreatePreAuthKeyRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    acl_tags: list[str] | None | NotGiven = Field(NOT_GIVEN, alias="aclTags")
    """Optional array value serialized in the `aclTags` wire field."""
    ephemeral: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `ephemeral` wire field."""
    expiration: datetime.datetime | NotGiven = NOT_GIVEN
    """Optional `date-time`-formatted value serialized in the `expiration` wire field."""
    reusable: bool | NotGiven = NOT_GIVEN
    """Optional `boolean` value serialized in the `reusable` wire field."""
    user: str | NotGiven = NOT_GIVEN
    """Optional `uint64`-formatted value serialized in the `user` wire field."""

    @field_validator("expiration", mode="before")
    @classmethod
    def _validate_expiration(cls, value):
        validate_date_time("expiration", value)
        return value


class DeletePreAuthKeyOutputBody(BaseModel):
    """Typed representation of the `DeletePreAuthKeyOutputBody` API schema."""


class ExpirePreAuthKeyOutputBody(BaseModel):
    """Typed representation of the `ExpirePreAuthKeyOutputBody` API schema."""


class ExpirePreAuthKeyRequestBody(BaseModel):
    """Typed representation of the `ExpirePreAuthKeyRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    id: str | NotGiven = NOT_GIVEN
    """Optional `uint64`-formatted value serialized in the `id` wire field."""


class ListPreAuthKeysOutputBody(BaseModel):
    """Typed representation of the `ListPreAuthKeysOutputBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    pre_auth_keys: list[PreAuthKey] = Field(alias="preAuthKeys")
    """Required array value serialized in the `preAuthKeys` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["preAuthKeys"], {"preAuthKeys": "pre_auth_keys"})
        return value


class PreAuthKey(BaseModel):
    """Typed representation of the `PreAuthKey` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    acl_tags: list[str] = Field(alias="aclTags")
    """Required array value serialized in the `aclTags` wire field."""
    created_at: datetime.datetime = Field(alias="createdAt")
    """Required `date-time`-formatted value serialized in the `createdAt` wire field."""
    ephemeral: bool
    """Required `boolean` value serialized in the `ephemeral` wire field."""
    expiration: datetime.datetime
    """Required `date-time`-formatted value serialized in the `expiration` wire field."""
    id: str
    """Required `uint64`-formatted value serialized in the `id` wire field."""
    key: str
    """Required `string` value serialized in the `key` wire field."""
    reusable: bool
    """Required `boolean` value serialized in the `reusable` wire field."""
    used: bool
    """Required `boolean` value serialized in the `used` wire field."""
    user: User
    """Required object value serialized in the `user` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "user",
                "id",
                "key",
                "reusable",
                "ephemeral",
                "used",
                "expiration",
                "createdAt",
                "aclTags",
            ],
            {"aclTags": "acl_tags", "createdAt": "created_at"},
        )
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def _validate_created_at(cls, value):
        validate_date_time("createdAt", value)
        return value

    @field_validator("expiration", mode="before")
    @classmethod
    def _validate_expiration(cls, value):
        validate_date_time("expiration", value)
        return value


class PreAuthKeyOutputBody(BaseModel):
    """Typed representation of the `PreAuthKeyOutputBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    pre_auth_key: PreAuthKey = Field(alias="preAuthKey")
    """Required object value serialized in the `preAuthKey` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["preAuthKey"], {"preAuthKey": "pre_auth_key"})
        return value
