# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven

from ..validation import validate_date_time, validate_required, validate_uri


class ErrorDetail(BaseModel):
    """Typed representation of the `ErrorDetail` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    location: str | NotGiven = NOT_GIVEN
    """Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"""
    message: str | NotGiven = NOT_GIVEN
    """Error message text"""
    value: Any | NotGiven = NOT_GIVEN
    """The value at the given location"""


class ErrorModel(BaseModel):
    """Typed representation of the `ErrorModel` API schema."""

    model_config = ConfigDict(populate_by_name=False, arbitrary_types_allowed=True)

    detail: str | NotGiven = NOT_GIVEN
    """
    A human-readable explanation specific to this occurrence of the problem.

    @example "Property foo is required but is missing."
    """
    errors: list[ErrorDetail] | None | NotGiven = NOT_GIVEN
    """Optional list of individual error details"""
    instance: str | NotGiven = NOT_GIVEN
    """
    A URI reference that identifies the specific occurrence of the problem.

    @example "https://example.com/error-log/abc123"
    """
    status: int | NotGiven = NOT_GIVEN
    """
    HTTP status code

    @example 400
    """
    title: str | NotGiven = NOT_GIVEN
    """
    A short, human-readable summary of the problem type. This value should not change between occurrences of the error.

    @example "Bad Request"
    """
    type: str | NotGiven = NOT_GIVEN
    """
    A URI reference to human-readable documentation for the error.

    @example "https://example.com/errors/example"
    """

    @field_validator("instance")
    @classmethod
    def _validate_instance(cls, value):
        validate_uri("instance", value)
        return value

    @field_validator("type")
    @classmethod
    def _validate_type(cls, value):
        validate_uri("type", value)
        return value


class Node(BaseModel):
    """Typed representation of the `Node` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    approved_routes: list[str] = Field(alias="approvedRoutes")
    """Required array value serialized in the `approvedRoutes` wire field."""
    available_routes: list[str] = Field(alias="availableRoutes")
    """Required array value serialized in the `availableRoutes` wire field."""
    created_at: datetime.datetime = Field(alias="createdAt")
    """Required `date-time`-formatted value serialized in the `createdAt` wire field."""
    disco_key: str = Field(alias="discoKey")
    """Required `string` value serialized in the `discoKey` wire field."""
    expiry: datetime.datetime | None
    """Required `date-time`-formatted value serialized in the `expiry` wire field."""
    given_name: str = Field(alias="givenName")
    """Required `string` value serialized in the `givenName` wire field."""
    id: str
    """Required `uint64`-formatted value serialized in the `id` wire field."""
    ip_addresses: list[str] = Field(alias="ipAddresses")
    """Required array value serialized in the `ipAddresses` wire field."""
    last_seen: datetime.datetime | None = Field(alias="lastSeen")
    """Required `date-time`-formatted value serialized in the `lastSeen` wire field."""
    machine_key: str = Field(alias="machineKey")
    """Required `string` value serialized in the `machineKey` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    node_key: str = Field(alias="nodeKey")
    """Required `string` value serialized in the `nodeKey` wire field."""
    online: bool
    """Required `boolean` value serialized in the `online` wire field."""
    pre_auth_key: NodePreAuthKey = Field(alias="preAuthKey")
    """Required object value serialized in the `preAuthKey` wire field."""
    register_method: (
        Literal[
            "REGISTER_METHOD_UNSPECIFIED",
            "REGISTER_METHOD_AUTH_KEY",
            "REGISTER_METHOD_CLI",
            "REGISTER_METHOD_OIDC",
        ]
        | str
    ) = Field(alias="registerMethod")
    """Required enumerated value serialized in the `registerMethod` wire field."""
    subnet_routes: list[str] = Field(alias="subnetRoutes")
    """Required array value serialized in the `subnetRoutes` wire field."""
    tags: list[str]
    """Required array value serialized in the `tags` wire field."""
    user: User
    """Required object value serialized in the `user` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "id",
                "machineKey",
                "nodeKey",
                "discoKey",
                "ipAddresses",
                "name",
                "user",
                "lastSeen",
                "expiry",
                "preAuthKey",
                "createdAt",
                "registerMethod",
                "givenName",
                "online",
                "approvedRoutes",
                "availableRoutes",
                "subnetRoutes",
                "tags",
            ],
            {
                "approvedRoutes": "approved_routes",
                "availableRoutes": "available_routes",
                "createdAt": "created_at",
                "discoKey": "disco_key",
                "givenName": "given_name",
                "ipAddresses": "ip_addresses",
                "lastSeen": "last_seen",
                "machineKey": "machine_key",
                "nodeKey": "node_key",
                "preAuthKey": "pre_auth_key",
                "registerMethod": "register_method",
                "subnetRoutes": "subnet_routes",
            },
        )
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def _validate_created_at(cls, value):
        validate_date_time("createdAt", value)
        return value

    @field_validator("expiry", mode="before")
    @classmethod
    def _validate_expiry(cls, value):
        if value is not None:
            validate_date_time("expiry", value)
        return value

    @field_validator("last_seen", mode="before")
    @classmethod
    def _validate_last_seen(cls, value):
        if value is not None:
            validate_date_time("lastSeen", value)
        return value


class NodePreAuthKey(BaseModel):
    """Typed representation of the `NodePreAuthKey` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    acl_tags: list[str] = Field(alias="aclTags")
    """Required array value serialized in the `aclTags` wire field."""
    created_at: datetime.datetime | None = Field(alias="createdAt")
    """Required `date-time`-formatted value serialized in the `createdAt` wire field."""
    ephemeral: bool
    """Required `boolean` value serialized in the `ephemeral` wire field."""
    expiration: datetime.datetime | None
    """Required `date-time`-formatted value serialized in the `expiration` wire field."""
    id: str
    """Required `uint64`-formatted value serialized in the `id` wire field."""
    key: str
    """Required `string` value serialized in the `key` wire field."""
    reusable: bool
    """Required `boolean` value serialized in the `reusable` wire field."""
    used: bool
    """Required `boolean` value serialized in the `used` wire field."""
    user: User
    """Required object value serialized in the `user` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "user",
                "id",
                "key",
                "reusable",
                "ephemeral",
                "used",
                "expiration",
                "createdAt",
                "aclTags",
            ],
            {"aclTags": "acl_tags", "createdAt": "created_at"},
        )
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def _validate_created_at(cls, value):
        if value is not None:
            validate_date_time("createdAt", value)
        return value

    @field_validator("expiration", mode="before")
    @classmethod
    def _validate_expiration(cls, value):
        if value is not None:
            validate_date_time("expiration", value)
        return value


class User(BaseModel):
    """Typed representation of the `User` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    created_at: datetime.datetime = Field(alias="createdAt")
    """Required `date-time`-formatted value serialized in the `createdAt` wire field."""
    display_name: str = Field(alias="displayName")
    """Required `string` value serialized in the `displayName` wire field."""
    email: str
    """Required `string` value serialized in the `email` wire field."""
    id: str
    """Required `uint64`-formatted value serialized in the `id` wire field."""
    name: str
    """Required `string` value serialized in the `name` wire field."""
    profile_pic_url: str = Field(alias="profilePicUrl")
    """Required `string` value serialized in the `profilePicUrl` wire field."""
    provider: str
    """Required `string` value serialized in the `provider` wire field."""
    provider_id: str = Field(alias="providerId")
    """Required `string` value serialized in the `providerId` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(
            value,
            [
                "id",
                "name",
                "createdAt",
                "displayName",
                "email",
                "providerId",
                "provider",
                "profilePicUrl",
            ],
            {
                "createdAt": "created_at",
                "displayName": "display_name",
                "profilePicUrl": "profile_pic_url",
                "providerId": "provider_id",
            },
        )
        return value

    @field_validator("created_at", mode="before")
    @classmethod
    def _validate_created_at(cls, value):
        validate_date_time("createdAt", value)
        return value
