# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

from headscale_unofficial_sdk.client import NOT_GIVEN, NotGiven
from headscale_unofficial_sdk.types.shared import User

from ..validation import validate_required


class CreateUserRequestBody(BaseModel):
    """Typed representation of the `CreateUserRequestBody` API schema."""

    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True)

    display_name: str | NotGiven = Field(NOT_GIVEN, alias="displayName")
    """Optional `string` value serialized in the `displayName` wire field."""
    email: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `email` wire field."""
    name: str | NotGiven = NOT_GIVEN
    """Optional `string` value serialized in the `name` wire field."""
    picture_url: str | NotGiven = Field(NOT_GIVEN, alias="pictureUrl")
    """Optional `string` value serialized in the `pictureUrl` wire field."""


class DeleteUserOutputBody(BaseModel):
    """Typed representation of the `DeleteUserOutputBody` API schema."""


class ListUsersOutputBody(BaseModel):
    """Typed representation of the `ListUsersOutputBody` API schema."""

    users: list[User]
    """Required array value serialized in the `users` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["users"])
        return value


class UserOutputBody(BaseModel):
    """Typed representation of the `UserOutputBody` API schema."""

    user: User
    """Required object value serialized in the `user` wire field."""

    @model_validator(mode="before")
    @classmethod
    def _validate_required(cls, value):
        validate_required(value, ["user"])
        return value
