# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from typing import Any

from ..client import ClientConfig, LoggingConfig
from .api_keys import _ApiKeysNamespace
from .auth import _AuthNamespace
from .health import _HealthNamespace
from .nodes import _NodesNamespace
from .policy import _PolicyNamespace
from .pre_auth_keys import _PreAuthKeysNamespace
from .users import _UsersNamespace


class Headscale:
    def __init__(self, config: ClientConfig) -> None:
        self._config = config
        self.api_keys = _ApiKeysNamespace(config)
        self.auth = _AuthNamespace(config)
        self.nodes = _NodesNamespace(config)
        self.health = _HealthNamespace(config)
        self.policy = _PolicyNamespace(config)
        self.pre_auth_keys = _PreAuthKeysNamespace(config)
        self.users = _UsersNamespace(config)

    def set_logging_config(
        self, config: LoggingConfig | None = None, **fields: Any
    ) -> LoggingConfig:
        """Turn SDK logging on and configure it.

        Logging is OFF by default — this SDK reports nothing until you call this
        (or construct the client with logging enabled). Reports go to the endpoint
        this build was generated with, or to the endpoint you pass; with neither,
        nothing is sent. Pass enabled=False to turn logging back off.
        """
        if self._config.logging is None:
            self._config.logging = LoggingConfig()
        current = self._config.logging
        if config is not None:
            for key, value in vars(config).items():
                if key != "enabled":
                    setattr(current, key, value)
        current.enabled = True
        for key, value in fields.items():
            if not hasattr(current, key):
                raise TypeError(f"LoggingConfig has no field {key!r}")
            setattr(current, key, value)
        return current


__all__ = ["Headscale"]
