# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.api_keys import (
    create_api_key,
    create_api_key_sync,
    delete_api_key,
    delete_api_key_sync,
    expire_api_key,
    expire_api_key_sync,
    list_api_keys,
    list_api_keys_sync,
)


class _ApiKeysNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list = partial(list_api_keys, config)
        self.list.__doc__ = list_api_keys.__doc__
        self.list_sync = partial(list_api_keys_sync, config)
        self.list_sync.__doc__ = list_api_keys_sync.__doc__
        self.create = partial(create_api_key, config)
        self.create.__doc__ = create_api_key.__doc__
        self.create_sync = partial(create_api_key_sync, config)
        self.create_sync.__doc__ = create_api_key_sync.__doc__
        self.expire = partial(expire_api_key, config)
        self.expire.__doc__ = expire_api_key.__doc__
        self.expire_sync = partial(expire_api_key_sync, config)
        self.expire_sync.__doc__ = expire_api_key_sync.__doc__
        self.delete = partial(delete_api_key, config)
        self.delete.__doc__ = delete_api_key.__doc__
        self.delete_sync = partial(delete_api_key_sync, config)
        self.delete_sync.__doc__ = delete_api_key_sync.__doc__
