# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.auth import (
    auth_approve,
    auth_approve_sync,
    auth_register,
    auth_register_sync,
    auth_reject,
    auth_reject_sync,
)


class _AuthNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.approve = partial(auth_approve, config)
        self.approve.__doc__ = auth_approve.__doc__
        self.approve_sync = partial(auth_approve_sync, config)
        self.approve_sync.__doc__ = auth_approve_sync.__doc__
        self.register = partial(auth_register, config)
        self.register.__doc__ = auth_register.__doc__
        self.register_sync = partial(auth_register_sync, config)
        self.register_sync.__doc__ = auth_register_sync.__doc__
        self.reject = partial(auth_reject, config)
        self.reject.__doc__ = auth_reject.__doc__
        self.reject_sync = partial(auth_reject_sync, config)
        self.reject_sync.__doc__ = auth_reject_sync.__doc__
