# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.health import health, health_sync


class _HealthNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.health = partial(health, config)
        self.health.__doc__ = health.__doc__
        self.health_sync = partial(health_sync, config)
        self.health_sync.__doc__ = health_sync.__doc__
