# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.nodes import (
    backfill_node_ips,
    backfill_node_ips_sync,
    debug_create_node,
    debug_create_node_sync,
    delete_node,
    delete_node_sync,
    expire_node,
    expire_node_sync,
    get_node,
    get_node_sync,
    list_nodes,
    list_nodes_sync,
    register_node,
    register_node_sync,
    rename_node,
    rename_node_sync,
    set_approved_routes,
    set_approved_routes_sync,
    set_tags,
    set_tags_sync,
)


class _NodesNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.debug_create = partial(debug_create_node, config)
        self.debug_create.__doc__ = debug_create_node.__doc__
        self.debug_create_sync = partial(debug_create_node_sync, config)
        self.debug_create_sync.__doc__ = debug_create_node_sync.__doc__
        self.list = partial(list_nodes, config)
        self.list.__doc__ = list_nodes.__doc__
        self.list_sync = partial(list_nodes_sync, config)
        self.list_sync.__doc__ = list_nodes_sync.__doc__
        self.backfill_ips = partial(backfill_node_ips, config)
        self.backfill_ips.__doc__ = backfill_node_ips.__doc__
        self.backfill_ips_sync = partial(backfill_node_ips_sync, config)
        self.backfill_ips_sync.__doc__ = backfill_node_ips_sync.__doc__
        self.register = partial(register_node, config)
        self.register.__doc__ = register_node.__doc__
        self.register_sync = partial(register_node_sync, config)
        self.register_sync.__doc__ = register_node_sync.__doc__
        self.delete = partial(delete_node, config)
        self.delete.__doc__ = delete_node.__doc__
        self.delete_sync = partial(delete_node_sync, config)
        self.delete_sync.__doc__ = delete_node_sync.__doc__
        self.get = partial(get_node, config)
        self.get.__doc__ = get_node.__doc__
        self.get_sync = partial(get_node_sync, config)
        self.get_sync.__doc__ = get_node_sync.__doc__
        self.set_approved_routes = partial(set_approved_routes, config)
        self.set_approved_routes.__doc__ = set_approved_routes.__doc__
        self.set_approved_routes_sync = partial(set_approved_routes_sync, config)
        self.set_approved_routes_sync.__doc__ = set_approved_routes_sync.__doc__
        self.expire = partial(expire_node, config)
        self.expire.__doc__ = expire_node.__doc__
        self.expire_sync = partial(expire_node_sync, config)
        self.expire_sync.__doc__ = expire_node_sync.__doc__
        self.rename = partial(rename_node, config)
        self.rename.__doc__ = rename_node.__doc__
        self.rename_sync = partial(rename_node_sync, config)
        self.rename_sync.__doc__ = rename_node_sync.__doc__
        self.set_tags = partial(set_tags, config)
        self.set_tags.__doc__ = set_tags.__doc__
        self.set_tags_sync = partial(set_tags_sync, config)
        self.set_tags_sync.__doc__ = set_tags_sync.__doc__
