# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.policy import (
    check_policy,
    check_policy_sync,
    get_policy,
    get_policy_sync,
    set_policy,
    set_policy_sync,
)


class _PolicyNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.get = partial(get_policy, config)
        self.get.__doc__ = get_policy.__doc__
        self.get_sync = partial(get_policy_sync, config)
        self.get_sync.__doc__ = get_policy_sync.__doc__
        self.set = partial(set_policy, config)
        self.set.__doc__ = set_policy.__doc__
        self.set_sync = partial(set_policy_sync, config)
        self.set_sync.__doc__ = set_policy_sync.__doc__
        self.check = partial(check_policy, config)
        self.check.__doc__ = check_policy.__doc__
        self.check_sync = partial(check_policy_sync, config)
        self.check_sync.__doc__ = check_policy_sync.__doc__
