# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.pre_auth_keys import (
    create_pre_auth_key,
    create_pre_auth_key_sync,
    delete_pre_auth_key,
    delete_pre_auth_key_sync,
    expire_pre_auth_key,
    expire_pre_auth_key_sync,
    list_pre_auth_keys,
    list_pre_auth_keys_sync,
)


class _PreAuthKeysNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.delete = partial(delete_pre_auth_key, config)
        self.delete.__doc__ = delete_pre_auth_key.__doc__
        self.delete_sync = partial(delete_pre_auth_key_sync, config)
        self.delete_sync.__doc__ = delete_pre_auth_key_sync.__doc__
        self.list = partial(list_pre_auth_keys, config)
        self.list.__doc__ = list_pre_auth_keys.__doc__
        self.list_sync = partial(list_pre_auth_keys_sync, config)
        self.list_sync.__doc__ = list_pre_auth_keys_sync.__doc__
        self.create = partial(create_pre_auth_key, config)
        self.create.__doc__ = create_pre_auth_key.__doc__
        self.create_sync = partial(create_pre_auth_key_sync, config)
        self.create_sync.__doc__ = create_pre_auth_key_sync.__doc__
        self.expire = partial(expire_pre_auth_key, config)
        self.expire.__doc__ = expire_pre_auth_key.__doc__
        self.expire_sync = partial(expire_pre_auth_key_sync, config)
        self.expire_sync.__doc__ = expire_pre_auth_key_sync.__doc__
