# Code generated by Octri SDK Studio. DO NOT EDIT.
# This file is machine-generated from your OpenAPI spec.

from __future__ import annotations

from functools import partial

from ..client import ClientConfig
from ..methods.users import (
    create_user,
    create_user_sync,
    delete_user,
    delete_user_sync,
    list_users,
    list_users_sync,
    rename_user,
    rename_user_sync,
)


class _UsersNamespace:
    def __init__(self, config: ClientConfig) -> None:
        self.list = partial(list_users, config)
        self.list.__doc__ = list_users.__doc__
        self.list_sync = partial(list_users_sync, config)
        self.list_sync.__doc__ = list_users_sync.__doc__
        self.create = partial(create_user, config)
        self.create.__doc__ = create_user.__doc__
        self.create_sync = partial(create_user_sync, config)
        self.create_sync.__doc__ = create_user_sync.__doc__
        self.delete = partial(delete_user, config)
        self.delete.__doc__ = delete_user.__doc__
        self.delete_sync = partial(delete_user_sync, config)
        self.delete_sync.__doc__ = delete_user_sync.__doc__
        self.rename = partial(rename_user, config)
        self.rename.__doc__ = rename_user.__doc__
        self.rename_sync = partial(rename_user_sync, config)
        self.rename_sync.__doc__ = rename_user_sync.__doc__
